### ISSUE TITLE
cannot open libcurl_a.lib

### ISSUE THREAD

**Issue by ReiRokusanami0010** [yourWaifu/sleepy-discord#103]
I have libcurl_a.lib but it will be LNK 1104 can not open libcurl_a.lib.

**Comment by yourWaifu** [comment]
Ok, You know where the file on your system, right? Ok on visual studio go to your project properties -> VC++ Directories -> Library Directories -> edit and check the box called evaluated values. Make sure that you move libcurl_a.lib is in ``deps/lib`` and that ``deps/lib`` is listed as a library directory.

**Comment by ReiRokusanami0010** [comment]
The file exists in C: \ sleepy-discord-master.
Also, replacing the libcurl_a.lib file with deps / lib, LNK 1104 no longer occurs, but LNK 2019 occurred

[error contents]
LNK2019 An unresolved external symbol __imp__ldap_init was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 An unresolved external symbol __imp__ldap_unbind_s was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_set_option was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 An unresolved external symbol __imp__ldap_simple_bind_s was referenced in function _ldap_win_bind. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 An unresolved external symbol __imp__ldap_bind_s was referenced in function _ldap_win_bind. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_search_s was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_msgfree was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_err 2 string was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_first_entry was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_next_entry was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_first_attribute was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_next_attribute was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_get_values ​​_ len was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_value_free_len was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_get_dn was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ldap_memfree was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 Unresolved external symbol __imp__ber_free was referenced in function _Curl_ldap. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (ldap.obj) 1

LNK2019 An unresolved external symbol __imp__IdnToAscii @ 20 was referenced in function _curl_win32_idn_to_ascii. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (idn_win32.obj) 1

LNK2019 An unresolved external symbol __imp__IdnToUnicode @ 20 was referenced in function _curl_win32 _ sasii_to_idn. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (idn_win32.obj) 1

LNK 1120 19 outstanding external references hello C: \ sleepy-discord-master \ Debug \ hello.exe 1

**Comment by yourWaifu** [comment]
These error actually look familiar. try adding wldap32.lib. This is a windows library. You might also need some others.

**Comment by ReiRokusanami0010** [comment]
Thank you. Most of the errors have disappeared, but only three have been lost ...

```[error contents]
LNK2019 An unresolved external symbol __imp__IdnToAscii @ 20 was referenced in function _curl_win32_idn_to_ascii. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (idn_win32.obj) 1

LNK2019 An unresolved external symbol __imp__IdnToUnicode @ 20 was referenced in function _curl_win32 _ sasii_to_idn. hello C: \ sleepy-discord-master \ examples \ hello \ libcurl_a.lib (idn_win32.obj) 1

LNK 1120 2 outstanding external references hello C: \ sleepy-discord-master \ Debug \ hello.exe 1
```

**Comment by yourWaifu** [comment]
OK according to https://docs.microsoft.com/en-us/windows/desktop/api/winnls/nf-winnls-idntounicode
It looks like you need to link Normaliz.lib

**Comment by ReiRokusanami0010** [comment]
Thank you very much!
Succeeded the build!
