### ISSUE TITLE
Gateway Error 5002: Could not get the gateway

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#108]
I setup a different Ubuntu server and now I get this error 

> Error 5002: Could not get the gateway
> Error 5003: Connect initialization: invalid uri

I'm not quite sure what it means or why it occurs on this machine only.

**Comment by Brandantl** [comment]
It's because libcurl4-openssl-dev uninstalls libssl1.0-dev apparently on the newest Ubuntu. And it can't link without libssl1.0-dev because the newest libssl messes up the functions. I forgot how I fixed this on my 18.04 VM.

**Comment by Brandantl** [comment]
Does it have to be libcurl4-openssl-dev or could it be libcurl4-gnutls-dev or  libcurl4-nss-dev?

With the other two it just crashes. 

terminate called after throwing an instance of 'std::system_error'
  what():  context: asio.ssl error
Aborted (core dumped)

**Comment by yourWaifu** [comment]
I'm not sure, I've only used libcurl from the git repo and installed libssl-dev with apt

**Comment by Brandantl** [comment]
I'll compile libcurl from source then with libssl 1.0.

**Comment by Brandantl** [comment]
Thanks for the help I copied over libcurl from my 16.04 machine and was able to compile and run it.
