### ISSUE TITLE
Hello example can't compile

### ISSUE THREAD

**Issue by jedenastka** [yourWaifu/sleepy-discord#110]
Hi. I tired to try sleepy-discord again, so I compiled it and tired to compile one of examples. Here is full bash log:
https://pastebin.com/UXkS85rA
I'm using Debian 9.

**Comment by yourWaifu** [comment]
I recommend you use cmake instead, it's a lot easier since you wouldn't need to deal with this. https://yourwaifu.github.io/sleepy-discord/compile.html#cmake

Other then that, you can easily fix your issues by compiling cpr and linking it.

It should be something like this
```
cd deps/cpr
g++ -c -I ../include cpr/*.cpp
ar rv *.o -o libcpr.a
mv libcpr.a ../lib
```

**Comment by jedenastka** [comment]
Compiling with cmake don't make the "MAKEFILE" and returns following error:
https://pastebin.com/FTciXWVa

**Comment by jedenastka** [comment]
`grzesiek11@pecet:~$ cmake -V
CMake Error: The source directory "/home/grzesiek11/-V" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
grzesiek11@pecet:~$ cmake --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
grzesiek11@pecet:~$ 
`

But there isn't any update in Debian Stable repos...

**Comment by yourWaifu** [comment]
I've never used Debian, I used Ubuntu but I'm going to guess that you can found the latest version of cmake for Debian online. https://www.google.com/search?q=debian+cmake+3.12.1

**Comment by yourWaifu** [comment]
@Brandantl Actually, there's a big in gcc 4.8 that is later fixed in I think about gcc 5 that gives an error in the code that allows the library to figure out what time it is according to Discord.

**Comment by Plisp** [comment]
@jedenastka you need to link cpr
```
cd deps/cpr
# if this fails comment out the duplicated CURLE_SSL_CACERT case in error.cpp
g++ -c -I ../include cpr/*.cpp
ar rv libcpr.a *.o
mv libcpr.a ../lib
```
include the homemade json library in sleepy_discord.a (which the makefile doesn't compile)
```
make -f Makefile.linux  
gcc -c ../sleepy_discord/json.c -I ../include/sleepy_discord/
# recreate archive
ar rv libsleepy_discord.a *.o
```
then compile using
```
g++ -std=c++11 -I ../../include -I ../../deps -I ../../deps/include -I ../../include/sleepy_discord/IncludeNonexistent example0.cpp -L ../../buildtools -L ../../deps/lib/ -L /usr/lib -lsleepy_discord -lcurl -lssl -lcrypto -lpthread -lcpr -o example.out
```
The makefile *should* be responsible for compiling and linking the `json` library upon which `json_wrapper` depends.
