### ISSUE TITLE
Windows MSVC 15 compile error - can only inherit constructor from direct base

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#112]
d:\repo\sleepy-discord\include\sleepy_discord\message.h(50): error C3881: can only inherit constructor from direct base

**Comment by yourWaifu** [comment]
remove line 50

**Comment by Brandantl** [comment]
Thank you for the quick update that helped a lot. I'll leave this open until the issues been resolved on develop so people don't make duplicate posts.
