### ISSUE TITLE
the value associated with case '60' is already used

### ISSUE THREAD

**Issue by KiwiDch** [yourWaifu/sleepy-discord#117]
hello, I already compile several times "sleepy discord" but this time it's the first time that I have this error:
Error C2196 the value associated with box '60' is already in use
LNK1181 Error Can not Open Input File 'sleepy_discord.lib'
I do not know where it can prevent it but it is strange
i use Visual Studio 2017

**Comment by yourWaifu** [comment]
error c2196 seems to do a switch statement that maybe related to your code. I can't tell from the info given, usually visual studio gives a file and a line number with an error like this.

As for the 2nd, I'll need to know the location of sleepy_discord.lib, your library directories of your current vs project configuration, and the current vs project configuration.

**Comment by KiwiDch** [comment]
ah sorry,I forgot to mention that it happens during compilation after going through setup.py, I do not know the directory of sleepy_discord.lib because that's what I'm trying to have, this error come examples that are included in the solution.
![ddddddd](https://user-images.githubusercontent.com/34109672/46249487-2f895500-c42a-11e8-8d66-473a8ad61bbb.PNG)

**Comment by yourWaifu** [comment]
ok for c2196, go to ``deps\cpr\cpr\error.cpp`` and try to find any duplicate cases.

try seeing if compiling now fixes all your issues, if not look for sleepy_discord.lib, it should be in your Debug or Release folder that is automatically create by visual studio.

**Comment by KiwiDch** [comment]
I have already tried to solve the problem myself, but I have nothing unusual to find in the code and I have not found twice the same case, for information the compiler tells me that the error comes from " case CURLE_SSL_CACERT: "
![yy](https://user-images.githubusercontent.com/34109672/46249633-b5a69b00-c42c-11e8-8c67-02af017a3b29.PNG)

**Comment by yourWaifu** [comment]
Have you tried deleting that case?

**Comment by KiwiDch** [comment]
it seems to solve the problem, thanks
