### ISSUE TITLE
[Feature request] Rich Embed support

### ISSUE THREAD

**Issue by KaKi87** [yourWaifu/sleepy-discord#121]
Hello,

It would be great to have Rich Embed support,

Thanks !

https://leovoel.github.io/embed-visualizer/

![Discord Rich Embed template](https://i.stack.imgur.com/HRWHk.png)

**Comment by yourWaifu** [comment]
This feature is already available in the develop branch. The master branch is using an older system for parsing and serializing Discord JSON structures, while the develop branch is using an experimental way of parsing and serializing these structures. This feature will be merged into master once all remaining issues are ironed out, which most of it is.

Here's an example of what it looks in the current develop branch.
```cpp
SleepyDiscord::Embed embed;
embed.title = "Title";
embed.description = "Description";
embed.url = "https://somewhere.someplace";
embed.footer.text = "Footer Text";
client.sendMessage("channel_id", "message", embed);
```

**Comment by KaKi87** [comment]
Is this branch stable enough ?
Thanks.

**Comment by yourWaifu** [comment]
describe stable enough

**Comment by KaKi87** [comment]
Can a bot based on this branch stay online 24-7 without showing errors randomly ?
Thanks.

**Comment by yourWaifu** [comment]
It should last at least a whole week before the reconnect loop bug happens #115.
