### ISSUE TITLE
Cannot initialize object parameter of type 'SleepyDiscord::BaseDiscordClient' with an expression of type 'MyClientClass'

### ISSUE THREAD

**Issue by KaKi87** [yourWaifu/sleepy-discord#125]
Hello,

My IDE is telling me this :

![2018-11-27 11_33_03-download-cpr c__temp_ice-9 - _main cpp - clion](https://user-images.githubusercontent.com/21284089/49078652-dcbbf600-f23e-11e8-9ed1-769d6fdd57ac.png)

I have the same error for all SleepyDiscord methods.

Can you help me please ?

Thanks !

**Comment by yourWaifu** [comment]
Can you give me a lot of error messages from the compiler?

**Comment by WattMann** [comment]
Hey man, i gave up :D i thought i fixed it but i found new error, that i
don't have things like openSSL (which is writen is C so i cant compile it
in C++ compiler) and i have no clue how to add it there

ut 27. 11. 2018 o 19:49 Sleepy Flower Girl <notifications@github.com>
napísal(a):
