### ISSUE TITLE
Error 5002 and 5003

### ISSUE THREAD

**Issue by Rasikh-Qadeer** [yourWaifu/sleepy-discord#140]
I have used the python script to generate the deps. I've followed the rest of the instructions to build curl and built all of the libs and stuff for x64.

Everything compiles fine however I get Error 5002 and 5003 which is a Could not get the gateway and Connect initialization: invalid uri, respectively.

I'd like some help because never in my life I've made built any APIs / Projects of such massive scale and even though trying hard for 4 days I got this to compile properly and now these 2 errors are killing me inside.

**Comment by yourWaifu** [comment]
This can happen after compiling libcurl with openssl. I don't know the full details as to why this happens but I've already talked about this here. https://github.com/yourWaifu/sleepy-discord/issues/128#issuecomment-447676128

**Comment by Rasikh-Qadeer** [comment]
Thanks for responding @yourWaifu 

I looked into that #128 (comment) and added those 2 curl lines that were mentioned to fix the issue, re-compiled sleepy-discord and got the new lib, replaced it and tried compiling my project, after running, both the error 5002 and 5003 are gone but this one occurs:

context: asio.ssl error: asio.ssl error

**Comment by yourWaifu** [comment]
did you set ``"pathto/cacert.pem"`` to the path to the pem file?

**Comment by Rasikh-Qadeer** [comment]
Where is this located?

**Comment by yourWaifu** [comment]
you were suppose to download it. ```You could also make modifications to the CPR library to make it use [CA certificates from here](CA certificates from here)```

**Comment by Rasikh-Qadeer** [comment]
Oh my bad, downloaded it now, any recommendation where to place it just to avoid any further issues?

**Comment by yourWaifu** [comment]
I would place it at the output of the compiler or with the executable.

**Comment by Rasikh-Qadeer** [comment]
Trying to set a path to the cacert.pem and making sure the file exists in that directory but I'm probably doing something wrong because the error still exists...

**Comment by yourWaifu** [comment]
You can replace it with the first example, the one with a warning, to test to make sure that the 2nd example fixes the issue. If it fixes things then the 2nd example should fix the issues. If the first example fixes the issue but the 2nd one doesn't then I don't know.

**Comment by Rasikh-Qadeer** [comment]
Using only example 1 also gives the same error

**Comment by yourWaifu** [comment]
It looks like you are using Windows, remove the code. Instead, you should recompile libcurl. Compile libcurl with winssl, and then recompile sleepy discord.

**Comment by Rasikh-Qadeer** [comment]
I followed https://medium.com/@chuy.max/compile-libcurl-on-windows-with-visual-studio-2017-x64-and-ssl-winssl-cff41ac7971d and built libcurl_a with SSL, now there's no error on console but it dies with a exception:

![image](https://user-images.githubusercontent.com/16344370/50829073-1b2bf100-1365-11e9-9256-1ab2c373aa2d.png)

**Comment by Rasikh-Qadeer** [comment]
"For now, compiling for x64 doesn’t work just yet."

Is this still true?

**Comment by yourWaifu** [comment]
No, compiling for 64 but now works thanks to cmake

**Comment by yourWaifu** [comment]
You can try clearing the cache and doing it again and see if that fixes anything. You shouldn't be running into these issues on windows.

**Comment by Rasikh-Qadeer** [comment]
I've already started from scratch and completely clean directories about 5-8 times now, I'm unable to get x64 to work, it does compile fine and all but these two errors pop up.

First try success on x32.

**Comment by Rasikh-Qadeer** [comment]
Used a packet manager on Windows to pre-install dependencies for x64 and it works on x64 now.
