### ISSUE TITLE
Exception on last commit (cdf35bd)

### ISSUE THREAD

**Issue by Paket236** [yourWaifu/sleepy-discord#141]
I updated the source code to the last commit (cdf35bd). But when sending messages, an exception occurs. See the screenshot: https://yadi.sk/i/qaiyiIxKB86zTQ
However, this does not stop sending messages and new messages can be delivered (from the main thread).
Did I do something wrong or is there really a mistake?

In the last commit I liked the opportunity to get the serverID from the message. Is it possible in the previous commit?

**Comment by yourWaifu** [comment]
Hmm, I may have made a mistake. I'll test my bots for a bit longer and see if I can recreate it. Also when it happens please click retry to debug it and screenshot me the call stack.

**Comment by yourWaifu** [comment]
Ok I got the error right at start up. I forgot to list the field in the list of field. oops, I've gotten used to not needing to do this on the develop version. change this line https://github.com/yourWaifu/sleepy-discord/blob/cdf35bdec691696f70470743c60a6a55f5ac7f0e/sleepy_discord/message.cpp#L6 to
```cpp
"id", "channel_id", "guild_id", "content", "timestamp", "edited_timestamp", "tts",
```
