### ISSUE TITLE
SleepyDiscord::Server.channels returns an empty vector every time

### ISSUE THREAD

**Issue by Rasikh-Qadeer** [yourWaifu/sleepy-discord#149]
The code
```
void SendDiscordMessageToChannelName(const std::string& channelName, const std::string& message) {
	auto servers = Bot->getServers().vector();
	for(std::vector<SleepyDiscord::Server>::const_iterator it = servers.begin(); it != servers.end(); it++) {
		auto channels = it->channels;
		for(std::vector<SleepyDiscord::Channel>::const_iterator jt = channels.begin(); jt != channels.end(); jt++) {
			if(jt->name == channelName)
				Bot->sendMessage(std::stoll(std::string(jt->ID)), message);
		}
	}
}
```

However 'channels' vector is always empty, am I doing something wrong?

**Comment by yourWaifu** [comment]
I don't see anything wrong, it's working for me. What version and branch are you using?

Just so you know, if you can, I would use the id instead of channel name since channels can have the same name or change name. But if you are using this for when a user puts in the name of a channel then this is ok.

**Comment by Rasikh-Qadeer** [comment]
Using the master branch.

![image](https://user-images.githubusercontent.com/16344370/54532162-ef526a80-49a8-11e9-860d-d0eafea69e2e.png)

This is how the test server looks incase needed.

**Comment by yourWaifu** [comment]
Oh, I took a 2nd look at the code, and I see the problem. GetServers doesn't return servers with the channels. You can get them from getServer or the onServer event.

**Comment by Rasikh-Qadeer** [comment]
Changed to
```
auto channels = Bot->getServerChannels(it->ID.number()).vector();
```
