### ISSUE TITLE
IsArray assertion failure

### ISSUE THREAD

**Issue by Rasikh-Qadeer** [yourWaifu/sleepy-discord#158]
After the bot stays online for quite some time, this assertion fails and it just dies (Since I'm hooking up this library's bot with a game server, the server crashes once this assertion fails)

https://prnt.sc/nkd2nn

**Comment by yourWaifu** [comment]
I'll need more information to figure this out. 2nd what version are you using. If you used git to download the library do ``git git rev-parse HEAD``

**Comment by Rasikh-Qadeer** [comment]
Hm, pretty sure this is a master build but i'll try

**Comment by yourWaifu** [comment]
I don't think this is master build, it looks like the develop branch.

**Comment by yourWaifu** [comment]
You can also find git version information in ``include/sleepy_discord/version.h``
