### ISSUE TITLE
Role checking

### ISSUE THREAD

**Issue by Paket236** [yourWaifu/sleepy-discord#162]
How can I check that a discord member has a specific role? Suppose a discord member wrote a message, and if he does not have the desired role, then ignore.

**Comment by purge-dev** [comment]
you must first get the `ServerMember ` object of the member by using `getMember()`, then assign a vector `Role` object to that member object's roles list. cycle through that list using a for loop and check it against the roleID of the role you wish to check.

**Comment by Paket236** [comment]
Thanks! It works.
