### ISSUE TITLE
Give my docs a Halloween theme

### ISSUE THREAD

**Issue by yourWaifu** [yourWaifu/sleepy-discord#17]
Just for the month of October. I'll be once Halloween is over.

**Comment by yourWaifu** [comment]
Also if you have any cool ideas to add to the theme, please comment.

**Comment by yourWaifu** [comment]
In case, you can't find it, the source code to the docs are here https://github.com/yourWaifu/sleepy-discord/tree/docs

**Comment by yourWaifu** [comment]
oops, I made a mistake with the first message. It should be:

> I'll be reverting it back once Halloween is over.

**Comment by atiwiex** [comment]
An actual C++ discord lib Thanks.

**Comment by DonutDeflector** [comment]
I'll take a stab at doing this. Cheers!
