### ISSUE TITLE
Cannot specify link libraries for target "A18" which is not built by this project.

### ISSUE THREAD

**Issue by thedeepocean** [yourWaifu/sleepy-discord#170]
Everything works in the cmake command except at the last part it says

CMake Error at CMakeLists.txt:8 (target_link_libraries): Cannot specify link libraries for target "A18" which is not built by this project.

Here is my Cmake file:

```
#CMakeLists.txt
cmake_minimum_required (VERSION 3.6)
project(A18)

add_executable(A18, source.cpp)

add_subdirectory(external/sleepy-discord)
target_link_libraries(A18 sleepy-discord)
```

**Comment by yourWaifu** [comment]
you have a comma on this line ```add_executable(A18, source.cpp)```, I wouldn't call this an issue with my library. Cmake doesn't use ``,`` to separate parameters, it uses spaces.
