### ISSUE TITLE
Bad parsing for editMember mute/deaf

### ISSUE THREAD

**Issue by Warpten** [yourWaifu/sleepy-discord#185]
```cpp
		const std::string muteString = mute == -1 ? json::boolean(mute) : "";
		const std::string deafString = deaf == -1 ? json::boolean(deaf) : "";
```

This can't work, since if the value given for `mute` or `deaf` is anything other than `-1` (so basically, `true` / `false`, which is what most users would expect), these lines will always assign `""`.

Invert the condition.

On top of that, how am I supposed to pass properties as nullable (for example, **not** editing username ?)

**Comment by yourWaifu** [comment]
this isn't parsing, this is serialization. other then that, username can be empty I believe at signal don't edit.

**Comment by yourWaifu** [comment]
I've fixed this in https://github.com/yourWaifu/sleepy-discord/commit/70e1ef43831fd7d38d99a2121dfff1654941ff77

**Comment by Warpten** [comment]
thanks!
