### ISSUE TITLE
Linking errors on ServerMember

### ISSUE THREAD

**Issue by DizzasTeR** [yourWaifu/sleepy-discord#196]
Hey, I've been using this library for quite a while now and recently ran into a weird issue.

Check out this sample code:

```cpp
void Bot::onMessage(SleepyDiscord::Message message)
{
	if (message.author.bot) return;

	SleepyDiscord::ServerMember serverMember = getMember(message.serverID, message.author.ID);
}
```

Causes:

```2>   Creating library build/bot/Release/DDiscord.lib and object D:/dev/MTA/mta-discord-bot/build/bot/Release/DDiscord.exp
2>Bot.obj : error LNK2019: unresolved external symbol "public: __cdecl SleepyDiscord::ServerMember::ServerMember(class std::basic_string_view<char,struct std::char_traits<char> > const &)" (??0ServerMember@SleepyDiscord@@QEAA@AEBV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z) referenced in function "public: __cdecl SleepyDiscord::ObjectResponse<struct SleepyDiscord::ServerMember>::operator struct SleepyDiscord::ServerMember(void)" (??B?$ObjectResponse@UServerMember@SleepyDiscord@@@SleepyDiscord@@QEAA?AUServerMember@1@XZ)
2>build\bot\Release\DDiscord.dll : fatal error LNK1120: 1 unresolved externals
```

on GCC (When loading the DLL)
![image](https://user-images.githubusercontent.com/16344370/101976802-bbce6e00-3c6a-11eb-92d2-1e5c5377673b.png)

The linking completely fails on MSVC. The project builds and links on GCC but throws an exception (similar to msvc) when loading the bot DLL so basically its failing on both MSVC and GCC.

Any help would be appreciated.

**Comment by yourWaifu** [comment]
can you try the develop version?

**Comment by DizzasTeR** [comment]
I was firstly on master, then I switched to develop and it still didn't resolve it.

**Comment by yourWaifu** [comment]
it looks like a c++ standards mismatch, can you make sure that the library and the program being linked are using the same c++ version or both are running C++ versions higher then 17.

**Comment by DizzasTeR** [comment]
Well changed my CMAKE config file to
```cmake
set (CMAKE_CXX_STANDARD 20)
```

Both the program and sleepy-discord project are set to /std:c++latest (previously were /std:c++17)

and uhhhh funnily I'm getting more errors now.

**Comment by yourWaifu** [comment]
if you want to, you can try to enforce the use of string_view, there used to be a memory usage difference but not sure if that's still the case since a number of overhauls to json parsing. set the following preprocessor define for both the target and the shared library. ``nssv_CONFIG_SELECT_STD_STRING_VIEW`` defined here https://github.com/yourWaifu/sleepy-discord/blob/5682d4dc52d38ee16fb8f57fddf43d334467a360/include/sleepy_discord/nonstd/string_view.hpp#L24

**Comment by DizzasTeR** [comment]
Defined it for both the library and the program projects, still didn't help.

Just to mention that the extra errors are related to strings like

![image](https://user-images.githubusercontent.com/16344370/101977291-8297fd00-3c6e-11eb-88b3-7c0b33c7d710.png)

**Comment by yourWaifu** [comment]
hmm might need to add ``#include <string>`` to the top of json_wrapper.cpp. or the wrong c++ version was set.

**Comment by DizzasTeR** [comment]
So I added the ``#include <string>`` in json_wrapper.cpp which got rid of the to_string error. However this is showing up when sleepy-discord.lib is being generated:

![image](https://user-images.githubusercontent.com/16344370/101977942-1b307c00-3c73-11eb-8142-5382227a3fcc.png)

And then when I link sleepy-discord.lib with the program, it ends up failing because now there's a redefinition

**Comment by DizzasTeR** [comment]
I don't know what happened but now it just compiled successfully. I haven't changed anything in terms of configuration and stuff... so yeah closing it but thanks for trying to help me out.
