### ISSUE TITLE
In what point in the code/file connects the token of the bot to discord?

### ISSUE THREAD

**Issue by GDB-spur** [yourWaifu/sleepy-discord#199]
I would like to know this because I am curious to see how it works.

**Comment by yourWaifu** [comment]
It happens on the Send Identity function. This happens after connecting to Discord's gateway via WebSockets. Connecting starts some time after the run function is called. The call stack usally looks like this: ```
Send Identity
Sleepy discord :: on message
WebSockets client :: on massage
WebSockets Library stuff
Async library stuff
```


For HTTPS request, the token is sent in every request in the header.
