### ISSUE TITLE
Features with Sleepy

### ISSUE THREAD

**Issue by TheUNOGuy** [yourWaifu/sleepy-discord#206]
There's no discussions forum here so I'll ask here, does this c++ library have All the features as the python API?

**Comment by TheUNOGuy** [comment]
Actually I see it dosen't so yeah...

**Comment by yourWaifu** [comment]
Of course it wouldn't lol. They was never the goal. This library has a different set features that it's aiming for.

**Comment by TheUNOGuy** [comment]
May I know what kind of features?

**Comment by yourWaifu** [comment]
It's on the front page of the website https://yourwaifu.dev/sleepy-discord/

However, if you like different answer, I can say that this library is made with the idea of doing only what's asked and nothing more. Everything that you write is done exactly as stated. That does mean you need to write more code, and a steeper learning curve, but you get flexibility, lower overhead, and more lightweight bots.

If you care about features, there's library that help you make bots as easy as a library can like Discord.js and Discord.py, they'll do things like caching, commands, etc for you.
