### ISSUE TITLE
How to terminate client.run() ?

### ISSUE THREAD

**Issue by glblduh** [yourWaifu/sleepy-discord#210]
The title

**Comment by yourWaifu** [comment]
Not sure what you mean but you can stop the client with quit().

Is you want to use the main thread, you can call run on another thread or process.

**Comment by glblduh** [comment]
I used quit(), but it is listening for message and replying to them.

**Comment by yourWaifu** [comment]
just tested it, on the v8 branch at least.

**Comment by glblduh** [comment]
Oh maybe because I have the client.run() in a DLL file and the main function that the client.run() resides on is being called by the executable file.

**Comment by glblduh** [comment]
I got it to work, it just needed to be the same object that is used to run it.
