### ISSUE TITLE
Uploading Image file in an embed?

### ISSUE THREAD

**Issue by Jerick120** [yourWaifu/sleepy-discord#211]
Something like the following works perfectly, however the image url has to be a link to an image. I am looking for a way to upload an image from my project folder (or maybe postgres database sometime later) instead of having to use a url. Would that be possible?

```c++
sendMessage(message.channelID, "", SleepyDiscord::Embed(R"({"title" : "Embed Title", "image" : "https://image_url.com"})"));
```

**Comment by yourWaifu** [comment]
To an embed, no. But you can attach it to the message via upload image
