### ISSUE TITLE
Preventing crash if onError is handled?

### ISSUE THREAD

**Issue by AlexandrSMed** [yourWaifu/sleepy-discord#213]
Is there a way to prevent http client calling "abort()" whenever some request is malfunctioning and keep the client running instead? Would be handy to keep the bot up sometimes and just checking working logs, especially if `onError` function is overriden

**Comment by yourWaifu** [comment]
No, check out the docs for more info about this. https://yourwaifu.dev/sleepy-discord/docs/requests
