### ISSUE TITLE
Undeclared Definition

### ISSUE THREAD

**Issue by xx1182** [yourWaifu/sleepy-discord#22]
Hi, i would have send a pull, but i never used Git, or any of this repositories thing(maybe i should learn).
Anyhow in "error.h"
It misses the identifier "GENERAL_ERROR"

You can just add this code below 		GATEWAY_FAILED = 5002, //Could not get the gateway
GENERAL_ERROR = 58008, //Fun stuff, if you write this on a calculator and flip it it says "BOOBS"

to fix it.

Pheraps this was intentional, as a way for people to get their own error codes?

**Comment by yourWaifu** [comment]
Oops, I forgot to commit my new error codes. Thanks for noticing. I fixed it on the newest commit. Also, I recommend you learn how to do some version control, Anything can happen to your code, and nice to have more than one copy of it.
