### ISSUE TITLE
onguildmemberjoin and guildCreate(bot join on guild) events

### ISSUE THREAD

**Issue by TheLifeWorm** [yourWaifu/sleepy-discord#230]
What are their names(if there).

**Comment by yourWaifu** [comment]
https://github.com/yourWaifu/sleepy-discord/blob/0f090ffc883dd7f0212969c5bed9c2b1699b2a38/sleepy_discord/client.cpp#L517
https://github.com/yourWaifu/sleepy-discord/blob/0f090ffc883dd7f0212969c5bed9c2b1699b2a38/sleepy_discord/client.cpp#L492
