### ISSUE TITLE
Get user ID

### ISSUE THREAD

**Issue by rogermiranda1000** [yourWaifu/sleepy-discord#235]
According to [User.h](https://github.com/yourWaifu/sleepy-discord/blob/master/include/sleepy_discord/user.h) there's an id param that returns the user Snowflake, but running 'message.author.id.number()' gives an error: "error: ‘struct SleepyDiscord::User’ has no member named ‘id’".

**Comment by yourWaifu** [comment]
Capital I capital D. ID

**Comment by rogermiranda1000** [comment]
Thanks! Please update [the documentation](https://yourwaifu.dev/sleepy-discord/docs/reference/Classes/struct_sleepy_discord_1_1_user/) for future developers!

**Comment by rogermiranda1000** [comment]
Thanks! My bad, I didn't see the inherited argument from [the documentation](https://yourwaifu.dev/sleepy-discord/docs/reference/Classes/struct_sleepy_discord_1_1_user/).

**Comment by yourWaifu** [comment]
It's in the docs, under the inherited members section.
