### ISSUE TITLE
A lot of 'undefined reference to ...'

### ISSUE THREAD

**Issue by corruptmemry** [yourWaifu/sleepy-discord#236]
Hello, i'm trying to build my bot but i'm getting a lot of 'undefined reference to ...'
Here's the screenshot:
![image](https://user-images.githubusercontent.com/88046785/127673530-7169b4d7-2077-41ed-aaa6-62ac0a42d1fd.png)
Building with command `g++ source.cpp -I/usr/local/include/opus/ `

**Comment by yourWaifu** [comment]
It's pretty hard to build complex programs by manually entering the compiler command. As such, the library requires the use of the build tool CMake. Please read the docs for more info.
