### ISSUE TITLE
Const reference instead of copying?

### ISSUE THREAD

**Issue by fleshka4** [yourWaifu/sleepy-discord#237]
Why we have to copy each of these positions? We are using C++ to have a better performance. Let's replace it with const references
https://github.com/yourWaifu/sleepy-discord/blob/0f090ffc883dd7f0212969c5bed9c2b1699b2a38/include/sleepy_discord/client.h#L568

**Comment by yourWaifu** [comment]
Have you tested if it makes a difference. And besides, in most cases, it's meant to move the objects. I think it's better, I use std::move of anything.
