### ISSUE TITLE
hello example recieves message, but never responds. Same with rock-paper-scissors example.

### ISSUE THREAD

**Issue by Gazoo101** [yourWaifu/sleepy-discord#244]
I've compiled and run 2 sleepy-discord examples: 'hello' and 'rock-paper-scissors'.
In both examples, sleepy-discord connects as intended, receives messages, but doesn't send anything back to the channel.

I've fiddled with bot permissions, going as far as making it `Administrator` just to be sure no permissions are missing.

I've also tried adding the server intent (`client.setIntents(SleepyDiscord::Intent::SERVER_MESSAGES);`) present in the [documentation](https://yourwaifu.dev/sleepy-discord/docs/events), which appears to be missing from the 'hello' example.

But no luck. Still no message appears to get sent from sleepy-discord.

Any ideas of what I might be missing and what's keeping sleepy-discord from sending any message back to a channel?

**Comment by yourWaifu** [comment]
Not sure, HTTP Get request might be fine, HTTP Post request is used for sending messages, and the bot needs to have send message permission in the channel it wants to send, and the channel id needs to be correct.
