### ISSUE TITLE
how to get user input?

### ISSUE THREAD

**Issue by zZDOCZz** [yourWaifu/sleepy-discord#248]
like "!ban @user" how can i get the "@user" as a user input.
i did go through the documentation and i found nothing or maybe i am just blind

**Comment by Trongaming321** [comment]
Do you mean getting the mention if so its message.mentions[0] (using the zero as it puts all the mentioned in the message into a vector).
If you mean you want to get it as a string then the syntax is <@![The users id you are referencing here]>. E.G. <@!49285037473937>
