### ISSUE TITLE
createChannel doesn't exsit, and createTextChannel gives errors on use.

### ISSUE THREAD

**Issue by AngryUshanka** [yourWaifu/sleepy-discord#250]
createTextChannel(message.serverID, "channel"); on execution gives this error.
`Error 400: The request was improperly formatted, or the server couldn't understand it
Error 5005: {"type": ["Value \"text\" is not int."]}`
I cannot change the type value of this function.

createChannel doesn't exist at all and gives me an error. Despite existing in the documentation

**Comment by yourWaifu** [comment]
I believe this has been fixed in the develop version of the library
