### ISSUE TITLE
Can't get members of voice channel

### ISSUE THREAD

**Issue by FadedStatic** [yourWaifu/sleepy-discord#252]
The class "Channel" does not have option to get array of users in voice channel, I would need this to see if someone's still in the voice channel with my music bot otherwise it could be playing 24/7 and be wasting bandwidth.

Here is the class for voice channels situated in sleepy-discord:

```
struct Channel : IdentifiableDiscordObject<Channel> {
public:
		Channel() = default;
		//Channel(const std::string * rawJson);
		Channel(const json::Value & rawJSON);
		Channel(const nonstd::string_view & rawJSON);
		//Channel(const json::Values values);
		~Channel();
		
		enum ChannelType {
			CHANNEL_TYPE_NONE = -1,
			SERVER_TEXT       = 0,
			DM                = 1,
			SERVER_VOICE      = 2,
			GROUP_DM          = 3,
			SERVER_CATEGORY   = 4,
			GUILD_NEWS        = 5,
			GUILD_STORE       = 6
		} type = CHANNEL_TYPE_NONE;
		Snowflake<Server>      serverID;             //optional,                  used in server       channels
		int                    position = 0;         //optional,                  used in server       channels
		std::vector<Overwrite> permissionOverwrites; //optional,                  used in server       channels
		std::string            name;                 //optional,              not used in           DM channels
		std::string            topic;                //optional and nullable,     used in server  text channels
		bool                   isNSFW = false;       //optional,                  used in server       channels
		Snowflake<Message>     lastMessageID;        //optional,                  used in         text channels
		int                    bitrate = 0;          //optional,                  used in        voice channels
		int                    userLimit = 0;        //optional,                  used in        voice channels
		std::vector<User>      recipients;           //optional,                  used in all       DM channels
		std::string            icon;                 //optional and nullable,     used in group     DM channels
		Snowflake<User>        ownerID;              //optional,                  used in group     DM channels
		//Snowflake<>          applicationID;        //??????????????????????     used in group     DM channels
		Snowflake<Channel>     parentID;             //optional and nullable,     used in server       channels
		std::string            lastPinTimestamp;     //optional,                  used in         text channels

		JSONStructStart
			std::make_tuple(
				json::pair                           (&Channel::ID                   , "id"                   , json::REQUIRIED_FIELD        ),
				json::pair<json::EnumTypeHelper     >(&Channel::type                 , "type"                 , json::REQUIRIED_FIELD        ),
				json::pair                           (&Channel::serverID             , "guild_id"             , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::position             , "position"             , json::OPTIONAL_FIELD         ),
				json::pair<json::ContainerTypeHelper>(&Channel::permissionOverwrites , "permission_overwrites", json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::name                 , "name"                 , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::topic                , "topic"                , json::OPTIONAL_NULLABLE_FIELD),
				json::pair                           (&Channel::isNSFW               , "nsfw"                 , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::lastMessageID        , "last_message_id"      , json::OPTIONAL_NULLABLE_FIELD),
				json::pair                           (&Channel::bitrate              , "bitrate"              , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::userLimit            , "user_limit"           , json::OPTIONAL_FIELD         ),
				json::pair<json::ContainerTypeHelper>(&Channel::recipients           , "recipients"           , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::icon                 , "icon"                 , json::OPTIONAL_NULLABLE_FIELD),
				json::pair                           (&Channel::ownerID              , "owner_id"             , json::OPTIONAL_FIELD         ),
				json::pair                           (&Channel::parentID             , "parent_id"            , json::OPTIONAL_NULLABLE_FIELD),
				json::pair                           (&Channel::lastPinTimestamp     , "last_pin_timestamp"   , json::OPTIONAL_FIELD         )
			);
		JSONStructEnd
	};
```

I do not seem to see anything for members in a voice channel, this feature is otherwise available in other APIs such as discord.js, the original is a collection with snowflake and guildmember:

URL to docs:
https://discord.js.org/#/docs/main/stable/class/VoiceChannel?scrollTo=members

I was wondering if there was a way that I could otherwise do what I am trying to do, and help would be greatly appreciated.
If I manage to find a solution to my own issue, I'll post it below.

**Comment by yourWaifu** [comment]
Please understand that this library isn't designed like other Discord libraries. This library is more minimal in that it does only what's needed for your bot to keep ram and CPU usage low.

Other than that, you can keep track of the number of users in a voice channel via voice states.
```cpp
void onEditVoiceState(VoiceState & state) override {
    //someone joins/leaves/moves voice channels
}
```
and
``server.voiceStates`` only available during ``onServer`` event
with that, you can keep track of the users that are in the voice channel by updating the count as users join and leave voice channels.

**Comment by FadedStatic** [comment]
> Please understand that this library isn't designed like other Discord libraries. This library is more minimal in that it does only what's needed for your bot to keep ram and CPU usage low.
> 
> Other than that, you can keep track of the number of users in a voice channel via voice states.
> 
> ```c++
> void onEditVoiceState(VoiceState & state) override {
>     //someone joins/leaves/moves voice channels
> }
> ```
> 
> and `server.voiceStates` only available during `onServer` event with these, you can keep track of the users that are in the voice channel by updating the count as users join and leave voice channels.

That's unfortunate, I'm actually trying to get specific user ids from people in the channels. I'll try to find a way to do it anyways. I didn't know that this library was designed to be lightweight, that's also really cool.

**Comment by yourWaifu** [comment]
Voice states have user IDs, or at least it should.

**Comment by FadedStatic** [comment]
> Voice states have user IDs, or at least it should.

After experimenting a bit, I made a hacky solution which joins every voice call to see which members are actually in voice calls, but I think this is really annoying to some as the bot would have to join every single VC just to find the right one.
This would prove to be irritating to many people in my server so I just temporarily shut it down, interesting concept but I made a poor execution of it.

The ideal thing for me would to just find a way to add this property in myself using the discord api but I have no clue how sleepy-discord works, for now I have no clue how sleepy-discord interacts with discord's api but if you want to help me out so I don't need to do some source searching then that would be really poggers. 
Anyways once I figure it out I'm gonna attach my solution below, that's gonna be hella based but whatever.
Thanks for your help so far, you've helped me a lot.

**Comment by yourWaifu** [comment]
``onServer`` gives you voice states, use ``server.voiceStates``, this should tell you who on each voice channel and their voice state.

**Comment by yourWaifu** [comment]
I did some testing and this should work without needing to join a voice channel
```cpp
	void onServer(SleepyDiscord::Server server) override {
		if (server.ID == "202917641101246465") {
			std::cout << "Targeted Server Found\n";
			for (SleepyDiscord::VoiceState& voiceState : server.voiceStates) {
				std::cout << "Voice State:\n"
					"UserID: " << voiceState.userID.string() << "\n"
					"ChannelID: " << voiceState.channelID.string() << '\n';

			}
		}
	}
```
Mind you, it's important that you have the Intents set up correctly and your bot has the ``SleepyDiscord::Intent::SERVERS`` intent set up.
```cpp
client.setIntents(SleepyDiscord::Intent::SERVERS);
```
More info on using intents with this library here https://yourwaifu.dev/sleepy-discord/docs/connect-options#intents

**Comment by FadedStatic** [comment]
> I did some testing and this should work without needing to join a voice channel
> 
> ```c++
> 	void onServer(SleepyDiscord::Server server) override {
> 		if (server.ID == "202917641101246465") {
> 			std::cout << "Targeted Server Found\n";
> 			for (SleepyDiscord::VoiceState& voiceState : server.voiceStates) {
> 				std::cout << "Voice State:\n"
> 					"UserID: " << voiceState.userID.string() << "\n"
> 					"ChannelID: " << voiceState.channelID.string() << '\n';
> 
> 			}
> 		}
> 	}
> ```
> 
> Mind you, it's important that you have the Intents set up correctly and your bot has the `SleepyDiscord::Intent::SERVERS` intent set up.
> 
> ```c++
> client.setIntents(SleepyDiscord::Intent::SERVERS);
> ```
> 
> More info on using intents with this library here https://yourwaifu.dev/sleepy-discord/docs/connect-options#intents

Yeah I was testing and had a similar thing going on, this really helped as well!
Thanks, you've been a big help.
