### ISSUE TITLE
LNK1181 cannot open input file 'cpr.lib'

### ISSUE THREAD

**Issue by devrawr** [yourWaifu/sleepy-discord#257]
# CMakeLists.txt
```cmake
cmake_minimum_required (VERSION 3.13)

project (sleepy-horse)
add_executable(sleepy-horse sleepy-horse.cpp)	

# libraries
find_package(sleepy-discord CONFIG REQUIRED)
target_link_libraries(sleepy-horse sleepy-discord)
```

# Full Error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'cpr.lib'	C:\Users\Patrick\source\repos\sleepy-horse\out\build\x64-debug\sleepy-horse	C:\Users\Patrick\source\repos\sleepy-horse\out\build\x64-debug\LINK	1	
```

# Platform
* Visual Studio + CMake and vcpkg

Not entirely sure if there is any important information I'm leaving out, this is my first time using CMake.

Any help would be appreciated, thanks in advance.

**Comment by yourWaifu** [comment]
Can you give me the version you installed, with the version number

**Comment by devrawr** [comment]
> Can you give me the version you installed? the version number from vcpkg

![image](https://user-images.githubusercontent.com/96917554/156883521-42679986-e876-4ff5-b984-7c46b8fd8ca4.png)
this I presume?

**Comment by yourWaifu** [comment]
oh, yes this an issue I'm aware and I have a fix, I forgot to update it on VCPKG.  https://github.com/yourWaifu/vcpkg/commit/80b81d10f29450b0fd8954937c65da50d2bca443

**Comment by yourWaifu** [comment]
you need to uninstall, reinstall, then try reconfiguring

**Comment by devrawr** [comment]
big thanks, that indeed worked.
