### ISSUE TITLE
Error 429 5005

### ISSUE THREAD

**Issue by TheLifeWorm** [yourWaifu/sleepy-discord#261]
When the bot writes a lot at a time in the chat.
Happens
```Error 429: You've made too many requests
Error 5005: {
  "global": false,
  "message": "You are being rate limited.",
  "retry_after": 2.506
}
```
and it crashes.
std::terminate
![image](https://user-images.githubusercontent.com/48316246/166667979-7ba87d67-8fcc-4fd7-b95e-2394b873d919.png)

How not to get a crash?

**Comment by TheLifeWorm** [comment]
After `#define ASIO_NO_EXCEPTIONS` i get exception from sleepydiscord.
![image](https://user-images.githubusercontent.com/48316246/166706897-8ded3db4-71ea-4b93-b466-bcb6914b9cc1.png)
Is there any way to replace the exception?
for example to return an error code or something similar?

**Comment by yourWaifu** [comment]
The docs already has multiple ways to avoid a crash from there kinds of errors. https://yourwaifu.dev/sleepy-discord/docs/requests
2nd, you really should slow down if you're getting rate limited. Last, defining ASIO_NO_EXCEPTIONS here isn't going to help you. LoL 🤣

**Comment by TheLifeWorm** [comment]
Oh thank you. I now use .error()
