### ISSUE TITLE
Why is there an error?

### ISSUE THREAD

**Issue by logican710** [yourWaifu/sleepy-discord#262]
void onEditMessage(SleepyDiscord::MessageRevisions remessage)override
	{
		std::string a = remessage.RevisionsJSON.GetString();
		sendMessage(remessage.channelID, a);
		
	}

![bug message](https://user-images.githubusercontent.com/75520768/167362724-5263dd67-a140-47fe-b905-7b2828782a1a.png)

thanks

**Comment by yourWaifu** [comment]
it should be ```cpp
remessage.applyChanges(outOfDateMessage);
```
RevisionsJSON is not a json string, so it'll abort since the types don't match up.
I believe what you want is the internal function ``SleepyDiscord::json::stringify``

**Comment by logican710** [comment]
Thank you for your kind answer.
