### ISSUE TITLE
Is it possible to use only curl to perfome requests and etc without websocket and etc? 

### ISSUE THREAD

**Issue by wecand0** [yourWaifu/sleepy-discord#264]

**Comment by yourWaifu** [comment]
Yes but it's not recommend because there's no intented way to get messages or other interactions as they come in because there's no server that you can run using this library. This library is client only.

**Comment by yourWaifu** [comment]
Just don't call the client.run() function

**Comment by wecand0** [comment]
Thanks for rapid reply, your are the best!
If you have time, can you write a very small example how to use your great library only with curl, for example send message)
