### ISSUE TITLE
SLEEPY_VCPKG confusion

### ISSUE THREAD

**Issue by uis246** [yourWaifu/sleepy-discord#270]
For some reason find_package is hidden behind USE_VCPKG flag. Why? Find_package isn't something vcpkg-specific, it's part of cmake.

**Comment by uis246** [comment]
https://github.com/yourWaifu/sleepy-discord/blob/master/sleepy_discord/CMakeLists.txt#L204
This raises more questions. Why hide this at all?

**Comment by yourWaifu** [comment]
It's not hidden. The tutorial uses add subdirectory, but to use find_package cmake needs to know how to find said library. So you need a cmake that finds the package. I personally don't want to deal with that mess and so I lock it behind VCPKG.

**Comment by uis246** [comment]
I looked into cmake/Modules. Yep, no modules for those, sorry.

Still install() is unrelated to VCPKG
