### ISSUE TITLE
Random disconnection due to truncated stream

### ISSUE THREAD

**Issue by ookami125** [yourWaifu/sleepy-discord#31]
So my current setup is I'm running on windows with CPR and Websocket++ as I've been having trouble compiling uWebsockets. So after a minute or so of running your rock paper scissors or the hello program I get the error:

[2017-11-24 13:20:02] [error] handle_read_frame error: asio.ssl.stream:1 (stream truncated)
[2017-11-24 13:20:02] [info] asio async_write error: asio.ssl:336396495 (protocol is shutdown)
[2017-11-24 13:20:02] [fatal] handle_write_frame error: websocketpp.transport:2 (Underlying Transport Error)
[2017-11-24 13:20:02] [info] asio async_shutdown error: asio.ssl.stream:1 (stream truncated)
[2017-11-24 13:20:02] [disconnect] Disconnect close local:[1006,Underlying Transport Error] remote:[1000]

I understand that this is most likely a problem with CPR or Websocket++, but these we're downloaded using the automated setup so there might be a problem there and I was wondering If you had this working and if so what platform and library versions are you using?

**Comment by yourWaifu** [comment]
Many things can go wrong when it comes to an online connection to another. Now, I'm not 100% sure if this is the case, you could be the cause of a bad connection. The reason why I think so it because it's saying the streams were cut off, and that no close frame was sent.

**Comment by ookami125** [comment]
Okay I'm currently on a wireless connection so I'll try to move to a wire connection, if that doesn't work then I'll try to get my friend to run it. I'll basically run it in as many ways as possible to see what happens I'll post the results after I'm done.

**Comment by ookami125** [comment]
So the tests so far don't seem to be related to my internet.
(Test #1) (Is my internet bad with websockets?)
I setup an example with Websocket++ (pulled it directly from your project) and ran a test that connects to ws://demos.kaazing.com/echo and just constant sends ping and that ran uninterrupted until 7 mins later I ended it.

(Test #2) (is it the connection to discord bad)
So I set up a quick NodeJS project with Discord.js and the bot is up and running for quite a few minutes now (no timestamps to work off of) without any crashes or signs of any problems.

Is there any other tests you think I can run to see if it's a problem on my end? I might also build it using Ubuntu to see if that fixes the problem.

**Comment by yourWaifu** [comment]
hmm, I'll look a bit more into on my side, but I have to first fix my setup and commit that before I can do any testing.

**Comment by ookami125** [comment]
Okay thanks for your help. It'll be so nice to be able to make a discord bot with c++.

**Comment by yourWaifu** [comment]
I have tested my library, and I can't recreate it.

**Comment by yourWaifu** [comment]
OK, I ran some test, I ran 2 bots for 10 minutes on an old version, and 1 on the latest version for 16 minutes. Sadly, I couldn't recreate your recreate the errors.

**Comment by ookami125** [comment]
I'll see what I can do tomorrow, I'll try and monitor the program every way I know how.

**Comment by Kheartz** [comment]
I've been having this issue to. From what I've been seeing so far, the issue seems to be with this function in client.cpp

```
void BaseDiscordClient::resumeHeartbeatLoop() {
	if (!heartbeatInterval) return;

	if (nextHeartbeat <= getEpochTimeMillisecond()) {
		do nextHeartbeat += heartbeatInterval;
		while (nextHeartbeat <= getEpochTimeMillisecond()); //prevents spam

		if (!wasHeartbeatAcked) {
			reconnect(1006);
			return;
		}

		std::string str = std::to_string(lastSReceived);
		sendL("{\"op\":1,\"d\":" + str + "}");
		wasHeartbeatAcked = false;
		onHeartbeat();
	}
}
```
Sometimes, after the interval determined by heartbeatInterval, the nextHeartbeat variable may be +1 higher than getEpochTimeMillisecond(), thus not allowing the client to communicate with Discord in the required amount of time. I was able to fix this by dropping this if statement block. I wasn't sure of yourWaifu's intention with the if block so I refrained from making a pull request.

My modified version of the function:

```
void BaseDiscordClient::resumeHeartbeatLoop() {
	if (!heartbeatInterval) return;

	do nextHeartbeat += heartbeatInterval;
	while (nextHeartbeat <= getEpochTimeMillisecond()); //prevents spam

	if (!wasHeartbeatAcked) {
		reconnect(1006);
		return;
	}

	std::string str = std::to_string(lastSReceived);
	sendL("{\"op\":1,\"d\":" + str + "}");
	wasHeartbeatAcked = false;
	onHeartbeat();

}
```

**Comment by yourWaifu** [comment]
The if statement was there because resumeHeartbeatLoop is a public function. When running on a single thread you still have to send heartbeats and in that situation, resumeHeartbeatLoop needs to be called in the program's main loop to continue sending heartbeats on time.

**Comment by Kheartz** [comment]
If so, for now I have just made sure that the nextHeartbeat is updated 1 less value that what it was originally:

```
void BaseDiscordClient::resumeHeartbeatLoop() {
		if (!heartbeatInterval) return;

		int64_t currTime = getEpochTimeMillisecond();
		if (nextHeartbeat <= currTime) {
			do nextHeartbeat += heartbeatInterval - 1;
			while (nextHeartbeat <= currTime); //prevents spam

			if (!wasHeartbeatAcked) {
				reconnect(1006);
				return;
			}

			std::string str = std::to_string(lastSReceived);
			sendL("{\"op\":1,\"d\":" + str + "}");
			wasHeartbeatAcked = false;
			onHeartbeat();
		}
	}
```

**Comment by yourWaifu** [comment]
I think a better fix is to make resumeHeartbeatLoop return a true after it sends a heartbeat and if false will skip the sleep.

So the change might be something like this
before:
```cpp
do {
	resumeHeartbeatLoop();
	sleep(heartbeatInterval);
} while (ready);```

after:
```cpp
do {
	if (resumeHeartbeatLoop() == true)
		sleep(heartbeatInterval);
} while (ready);```

This way, when the heartbeat false or is 1 ms too early, it'll not sleep and try again.

**Comment by Kheartz** [comment]
Looks good. Just for completion:

```
bool BaseDiscordClient::resumeHeartbeatLoop() {
    if (!heartbeatInterval) return false;

    int64_t currTime = getEpochTimeMillisecond();
    if (nextHeartbeat <= currTime) {
        do nextHeartbeat += heartbeatInterval;
        while (nextHeartbeat <= currTime); //prevents spam

        if (!wasHeartbeatAcked) {
            reconnect(1006);
            return false;
        }

        std::string str = std::to_string(lastSReceived);
        sendL("{\"op\":1,\"d\":" + str + "}");
        wasHeartbeatAcked = false;
        onHeartbeat();
        return true;
    }

    return false;
}
```
Been running for a while now with no interruptions.

**Comment by yourWaifu** [comment]
@ookami125 Please leave a comment if you are still having issues?

**Comment by ookami125** [comment]
Sorry for the late reply job searching took priority over programming for a little while. Yes, in the problem seems to have been fixed for me in the master branch thank you for the help.
