### ISSUE TITLE
impossible to compile : impossible to open "sleepy_discord/websocketpp_websocket.h": no such file or directory

### ISSUE THREAD

**Issue by KiwiDch** [yourWaifu/sleepy-discord#32]
Hi, I would like to compile sleepy_discord but visual studio tells me that it is impossible to open websocketpp_websocket.h, I tried everything but no result, I use python for installation :/
C1083 'sleepy_discord/websocketpp_websocket.h' : No such file or directory	C:\Users\elian\Desktop\sleepy\sleepy-discord-master\examples\hello\example0.cpp

**Comment by yourWaifu** [comment]
Did you forget to unzip the zip file?

**Comment by KiwiDch** [comment]
I did not forget any unzip, i said above, i use setup.py who did all the work, i do not see anything else to unzipper

**Comment by yourWaifu** [comment]
the setup.py doesn't have anything to do with that file, I'm going to guess it may have to do with the project properties. Please check that VC++ Directories -> Include Directories list \sleepy_discord\include or $(SolutionDir)include

**Comment by KiwiDch** [comment]
I just tried, but it does not change anything

**Comment by yourWaifu** [comment]
can you send me your files? so that I can see if it's just an issue on your end.

**Comment by KiwiDch** [comment]
no problem, here is the mega link: https://mega.nz/#!zFIhBZrY!ZdPnzLld4vJHITMUfWLi93yYTqZ7EH0gu1RozxjPXdk

**Comment by yourWaifu** [comment]
nope, it compiled without an issues on my end

**Comment by yourWaifu** [comment]
OK, I think I know what the issue is, you have had it set to this
![image](https://user-images.githubusercontent.com/16181109/33503940-8d233a56-d6b3-11e7-8e6d-680ce981ee1b.png)
My Visual Studio project files don't support this just yet, so change this to 
![image](https://user-images.githubusercontent.com/16181109/33503970-ac891690-d6b3-11e7-904f-943da3843296.png)
for now

**Comment by KiwiDch** [comment]
ok I just did it but, I end up with 2690 errors of the same type: / but I think it comes from the compiler sorry French on the image.
![wut](https://user-images.githubusercontent.com/34109672/33504325-4ce9cce6-d6e7-11e7-987f-39fca88d8b3b.PNG)

**Comment by yourWaifu** [comment]
I don't remember ever using cstdio

**Comment by KiwiDch** [comment]
maybe it comes from dependencies? or so visual stuido tries to load the files even if they are not using

**Comment by yourWaifu** [comment]
I looked up one of the errors and this came up https://stackoverflow.com/questions/42777424/visual-studio-2017-errors-on-standard-headers hopes this helps

**Comment by KiwiDch** [comment]
thank you very much, it has fixed me the problem but it remains 4 error:
![cecec](https://user-images.githubusercontent.com/34109672/33505458-a2da1576-d6eb-11e7-9576-5aba19a3e645.PNG)

**Comment by yourWaifu** [comment]
oh you need to compile curl, I havn't automated that task yet and it's still an important part, I have a tutoral here. https://yourwaifu.github.io/sleepy-discord/link.html

**Comment by KiwiDch** [comment]
Ok I will test, thank you, it's cool to help me

**Comment by KiwiDch** [comment]
thank you !!! i have sleepy-discord.lib, my problem is resolved
