### ISSUE TITLE
Rate-limits seemly lasting forever

### ISSUE THREAD

**Issue by yourWaifu** [yourWaifu/sleepy-discord#34]
I was made aware that after getting rate limited after quickly sending too many http requests, the limit isn't lifted even after 30 minutes.

**Comment by ookami125** [comment]
I know the problems that cause this. first getEpochTimeMillisecond() doesnt seem to return the correct time I've replaced it with this code 
```
const int64_t BaseDiscordClient::getEpochTimeMillisecond() {
	int64_t now = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
	return now;
}
```
second the retry time is returned in seconds instead of milliseconds so client.cpp about line 42 should be something like  `if (nextRetry <= getEpochTimeMillisecond() / 1000)` and line 85 `nextRetry = getEpochTimeMillisecond()/1000 + std::stoi(response.header["Retry-After"]);`

**Comment by ookami125** [comment]
also note that the setError on line 107 is kind of incorrect as having 0 remaining doesnt mean you've made too many requests this confused me at first because requesting the server list will Rate Limit you every time when it comes to that at least.

**Comment by yourWaifu** [comment]
After those comments, I've been thinking if the time from ``getEpochTimeMilliseconds()`` should be compared to time from Discord. I was thinking that it may be better to instead get the delta Discord reset time (``discordReset - discordNow``(I think Discord also sends the Date in the HTTP response header, and we can use that as the time according to Discord)) and add that to ``getEpochTimeMilliseconds()`` and use that as ``nextRetry``. I was thinking that even if we fix ``getEpochTimeMilliseconds()`` that it might still be possible for a time difference between ``getEpochTimeMilliseconds()`` time and Discord time. Taking time from Discord would be more accurate to Discord.

Also by the way, ``Retry-After`` is in milliseconds not seconds, but ``Reset`` is in seconds. https://discordapp.com/developers/docs/topics/rate-limits

**Comment by ookami125** [comment]
oh okay, sorry I didn't completely confirm my solution but at least the idea is out there now.
