### ISSUE TITLE
uploadFile doesn't work

### ISSUE THREAD

**Issue by Kheartz** [yourWaifu/sleepy-discord#38]
Function doesn't seem to properly upload images. 400 ERROR throws. This is likely due to the format of the JSON object:

```
ObjectResponse<Message> BaseDiscordClient::uploadFile(Snowflake<Channel> channelID, std::string fileLocation, std::string message) {
		return request(Post, "channels/" + channelID + "/messages",
			{ { "content", message },
			{ "file", filePathPart{fileLocation} }
		}
		);
```

I've tried different formats looking at the Discord API documentation, but still couldn't get it to work myself.

Ex

**Comment by yourWaifu** [comment]
I was able to get it working again.
![image](https://user-images.githubusercontent.com/16181109/33914386-edca0c8e-df6b-11e7-9c46-b8b862a48a1f.png)
Well, kind of.

**Comment by yourWaifu** [comment]
Fixed thanks for reporting, the bug was caused by a few bugs, first it was an Content-Length that was being and 2nd was the content of the message being deallocated.
