### ISSUE TITLE
"How to Compile Sleepy Discord" documentation has conflicting images and instructions

### ISSUE THREAD

**Issue by Lypank** [yourWaifu/sleepy-discord#39]
Currently the documentation supplies two main ways of building the library. I was having problems with the "automated" system so I chose to do it by hand. Choosing to manually build it, I've ran into conflicting or contradicting instructions or photos. 

Working strictly within the created "deps" folder you're asked to move the cpr-master folder from within the cpr zip then rename it to cpr.

Then from the context which I understood the instructions I'm asked to then take the "include" folder from within the newly renamed cpr folder and move it back to the "deps" folder.

Currently, the photos match up with what I'm asked to do.

Then I was asked to reenter the "cpr" folder and navigate to "opt/curl" then place the contents of the downloaded "curl" folder into "opt/curl." The final step within the "curl" folder involves building it via the supplied "buildconf.bat" if on Windows.

Moving onto the addition of Websocket++ and Asio 1.10.8 I ran into the first issue.

You are asked to move the downloaded "websocketpp" folder into "deps/include" and in addition you are asked to move the "asio" folder and the "asio.hpp" file within "asio-1.10.8/include" to your "deps/include" folder. If you check against the provided photos you'll find that "deps/include" will only ever contain the "cpr" and "openssl" folder, while the photo shows that "deps" will instead contain the folders and file you are asked to move to the "deps/include" folder.

The second set of instructions regards OpenSSL. Using the [npcglib.org](https://www.npcglib.org/~stathis/blog/precompiled-openssl/) website provided you'll find that the VS2017 7z contains another "openssl" folder within it. Going strictly off of the photos I dragged the "include/openssl" folder to the created "deps/include/openssl" folder.

I took some time to check this against the folder structure of the automated setup and found that the automated "deps/include/openssl" does not contain another "openssl" folder but the contents of the downloaded "include/openssl."

I'm having issues with the automated setup and I'm having trouble clearly understanding what is asked within the manual setup.

**Comment by yourWaifu** [comment]
Ok, I reread the instruction and they are correct. The images are however outdated. here are the new images 
![image](https://user-images.githubusercontent.com/16181109/34366543-f70629cc-ea6a-11e7-9b3b-97e5fe8427b2.png)
![image](https://user-images.githubusercontent.com/16181109/34366559-1b3f8342-ea6b-11e7-94a2-c67d31499411.png)
