### ISSUE TITLE
The startsWith function is not working properly

### ISSUE THREAD

**Issue by DaYWhiTe** [yourWaifu/sleepy-discord#41]
I'm new to c ++.
the startsWith command import function does not work.

const char * parameter is incompatible
const char value can not be converted to char *

**Comment by yourWaifu** [comment]
This isn't a bug or an issue with startsWith, you just need to use a char*. It's better to use a std::string with the function std::string::data(). For example

```cpp
std::string startMessage = "ssssss";
if (message.startsWith(startMessage.data())) {
    //code
}```

However, I'm most likely going to rewrite this function to use a std::string instead as this is most likely a function made when this library was a c library.

**Comment by DaYWhiTe** [comment]
then your example is incorrect

`#include "sleepy_discord/websocketpp_websocket.h"

class myClientClass : public SleepyDiscord::DiscordClient {
public:
	using SleepyDiscord::DiscordClient::DiscordClient;
	void onMessage(SleepyDiscord::Message message) {
		if (message.startsWith("whcg hello"))
			sendMessage(message.channelID, "Hello " + message.author.username);
	}
};

int main() {
	myClientClass client("token", 2);
	client.run();
}`

**Comment by yourWaifu** [comment]
No, it's correct. Because that is a char*. Or are you saying that you can't get the example to compile?

**Comment by DaYWhiTe** [comment]
yes i tried but did not work

**Comment by yourWaifu** [comment]
well I'm going to guess that you used a char, correct? If so, that would make sense why it wouldn't work, it's expecting a pointer to a array of chars.

**Comment by DaYWhiTe** [comment]
I try to do as you do, but it does not work.

**Comment by yourWaifu** [comment]
Oh I see, I made a mistake since std::string::data() returns a const char* instead of a char*. I'm not sure that this will work but do something like ``const_cast<char*>(startMessage.data())``

**Comment by yourWaifu** [comment]
I'll update the library do use a std::string, since everything else in my library uses std::string, it should be a very simple change.

**Comment by DaYWhiTe** [comment]
thanks I am new to c ++ and I think that I can learn by writing a simple bot in the discord
