### ISSUE TITLE
addReaction does not work

### ISSUE THREAD

**Issue by drunkenhammer** [yourWaifu/sleepy-discord#43]
So i called addReaction(this->serverID, this->messageID, "%F0%9F%98%95"); what happened is that no reaction appeared on the chat so that i used the emoji that was used in the documentation and still this issue. 

 the serverID and messageID was correct as i was able to edit the message within that channel.

However when i checked the console, it gave this long gibberish error.

Console error here...
![image](https://user-images.githubusercontent.com/23382734/35074671-cfd2b650-fba3-11e7-90b3-5b5f90a380c1.png)

**Comment by yourWaifu** [comment]
The error is stating that the content length field is missing. I don't know how that is possible. But I'll look into it.

**Comment by yourWaifu** [comment]
OK, I see why this happened, and can easily fix it. 
The issue happens here https://github.com/yourWaifu/sleepy-discord/blob/master/sleepy_discord/client.cpp#L65.
Adding this should fix this error
```cpp
else header.push_back({ "Content-Length", "0" });
```
