### ISSUE TITLE
Having trouble compiling

### ISSUE THREAD

**Issue by BMWSurfer** [yourWaifu/sleepy-discord#44]
Hi there!

When I try to compile SleepyDiscord it throws all these lovely errors: https://pastebin.com/DyJZGwT1. For the most part they are "The command exited with code 9009". Im on windows 10, using VS15 and Websocket++. I used the setup script and everything went smoothly until I went to compile. What am I missing?

**Comment by yourWaifu** [comment]
Umm it looks like you are compiling the WebAssembly Client and not the library. ![](https://user-images.githubusercontent.com/16181109/34865679-a2c8abf2-f747-11e7-8202-6c8f4d420990.png)

**Comment by BMWSurfer** [comment]
It worked! Thanks so much!
