### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by apevape** [yourWaifu/sleepy-discord#45]
Hello.

I followed your tutorial on how to link sleepy discord to my project, but it doesn't work for me.

This is how I did it:

![devenv_2018-01-29_21-24-13](https://user-images.githubusercontent.com/35935751/35532509-c42e6c7c-053a-11e8-9df8-2102ed914021.png)

![devenv_2018-01-29_21-24-33](https://user-images.githubusercontent.com/35935751/35532523-d0ce127a-053a-11e8-95b0-a8214521365a.png)

curl libraries are in deps\lib and sleepy_discord.lib is in release
![explorer_2018-01-29_21-25-56](https://user-images.githubusercontent.com/35935751/35532586-00208e86-053b-11e8-94e1-61358ac0afa5.png)

![devenv_2018-01-29_21-26-19](https://user-images.githubusercontent.com/35935751/35532600-0f8e47a0-053b-11e8-882e-1e801adb897b.png)

But..
![devenv_2018-01-29_21-22-55](https://user-images.githubusercontent.com/35935751/35532475-a5a702c8-053a-11e8-830b-4b9004972cfe.png)

**Comment by yourWaifu** [comment]
It looks like you are missing ``deps/include/websocketpp/config/asio_client.hpp``, can you show what's inside your websocketpp folder?

**Comment by apevape** [comment]
Thanks! You were right, it works now.
