### ISSUE TITLE
Not much of an issue

### ISSUE THREAD

**Issue by TheLearneer** [yourWaifu/sleepy-discord#46]
I wanted to know more about this project, and talking about this. I do guess this project has a discord server,
I would love to get in touch with the devs as i am also a C++ programmer.

**Comment by SLASHLogin** [comment]
As far as I know it don't have any what would be a nice idea to make one. It would help developing it in a group

**Comment by yourWaifu** [comment]
You can talk to me directly via Discord if you like. I'm Sleepy Flower Girl on Discord, and in the [Discord API server](https://discord.gg/discord-api).
