### ISSUE TITLE
Cannot open libcurl_a.lib

### ISSUE THREAD

**Issue by AppaXD** [yourWaifu/sleepy-discord#47]
Probably some stupid nooby mistake, but when I try to build sleepy_discord it requires the cpr files, and after I got those, it said it couldn't open libcurl_a.lib. Help would be appreciated lol

**Comment by yourWaifu** [comment]
Take a look at the preparing step from this link, it should tell you how to get that file add where to place it. https://yourwaifu.github.io/sleepy-discord/link.html#visual-studio

**Comment by AppaXD** [comment]
I've followed the steps twice now, and it's still giving me the same error.

**Comment by yourWaifu** [comment]
So you have libcurl_a.lib in ``deps/lib``?
