### ISSUE TITLE
Cannot open source file "sleepy_discord/websocketpp_websocket.h"

### ISSUE THREAD

**Issue by AppaXD** [yourWaifu/sleepy-discord#51]
I've followed the steps of https://yourwaifu.github.io/sleepy-discord/link.html#visual-studio twice, and it's still giving me the error. I have the include directories in the right order, as well as the library directories and additional dependencies.

**Comment by yourWaifu** [comment]
can I see your include directories as well as the folder that has the file ``websocketpp_websocket.h`` with it's file location?

**Comment by AppaXD** [comment]
Sure.
![image](https://user-images.githubusercontent.com/24938580/36387921-4b9a8230-1568-11e8-8346-599432701e5c.png)
![image](https://user-images.githubusercontent.com/24938580/36387947-61712208-1568-11e8-882f-36c2b1a64dec.png)

**Comment by yourWaifu** [comment]
can I see the file path to ``websocketpp_websocket.h``? It should be something like this ``Documents\sleepy-discord\include\sleepy_discord``, and also check to make sure that you have the current configuration set to the one you are editing. Here I draw some arrows and circle for things to look out for. 
![image](https://user-images.githubusercontent.com/16181109/36389412-f9c8557c-156c-11e8-82aa-a240a6716940.png)

**Comment by AppaXD** [comment]
Oh, well. I'm an idiot. I had configurations set to debug and platform wet to Win32.
