### ISSUE TITLE
Random crashes related to "endpoint_impl.hpp"

### ISSUE THREAD

**Issue by HunterCop224** [yourWaifu/sleepy-discord#52]
I'm getting seemly random crashes (or exceptions) after launching a compiled build, anywhere from one hour after launching to 36 hours.

This is outside a test environment, as in, I have built a "release" version in Visual Studio and am launching an exe. Currently the bot I have built only read/writes files and tracks user data, there is nothing going on passively, only the onMessage event with an library of functions that run if onMessage starts with something.

The exception is caught by windows and offers Visual Studio debugging, which points to line 230 in "endpoint_impl.hpp". I'm a noob at C++but from what I can understand the network connection is being closed for some reason. I've build SleepyDiscord by the (confusing) guide offered using CPR, Websocket++, and uWebSockets.

I am running on Windows Server 2016 x64, and built the bot with 32 bit settings for the release exe.

Any help is appreciated, if I need to provide more information just say and I'll collect it.

**Comment by yourWaifu** [comment]
This one? https://github.com/zaphoyd/websocketpp/blob/378437aecdcb1dfe62096ffd5d944bf1f640ccc3/websocketpp/impl/endpoint_impl.hpp#L230

It's hard to say what's causing the issue without knowing the error. The value ``ec`` may help, looking at the code, it's type is a ``std::error_code`` or a ``boost::system::error_code`` according to this file https://github.com/zaphoyd/websocketpp/blob/378437aecdcb1dfe62096ffd5d944bf1f640ccc3/websocketpp/common/system_error.hpp. While in debugging mode in Visual Studio, you should be able to read the value. This should give us a bit more info about what went wrong.

It would also be nice if you can tell me the last time you updated or the date of when you downloaded the library. I don't know if you are using the latest version, and it was already fixed. The Windows file manager should info of when you downloaded the file and it would be useful to have.

**Comment by HunterCop224** [comment]
Oh I apologize I didn't think of that, knew I was missing something. I believe I'm on the latest version, I built the SleepyDiscord libraries in Visual Studio on February 19th. I've been running and screen shotting every time my bot disconnects and have screenshots for that below.

There's three points where I got a notice from debugging this time.

1st: client.cpp line 317
```316		void BaseDiscordClient::disconnectWebsocket(unsigned int code, const std::string reason) {
317			disconnect(code, reason);
318			onDisconnect();
319		}```

2nd: endpoint_impl.hpp line 230
```
224		template <typename connection, typename config>
225		void endpoint<connection,config>::close(connection_hdl hdl, close::status::value
226		    const code, std::string const & reason)
227		{
228		    lib::error_code ec;
229		    close(hdl,code,reason,ec);
230		    if (ec) { throw exception(ec); }
231		}
```

3rd: websocketpp_websocket line 70
```
69		void WebsocketppDiscordClient::disconnect(unsigned int code, const std::string reason) {
70			this_client.close(handle, code, reason);
71		}
```

All three have the code as 1006 and the reason as "". Other variables come back too such as:
heartbeatInterval = 7
status = 4294967295
wasHeartbeatAcked = true (116)

There are also these two crashes which seem similar, however I did not have the code or reason for them.
![lyra2](https://user-images.githubusercontent.com/34903084/36883802-6889f334-1da2-11e8-80a5-6052ae205da3.PNG)
![lyra3](https://user-images.githubusercontent.com/34903084/36883803-689e92a8-1da2-11e8-8834-de7e45e68916.PNG)

**Comment by yourWaifu** [comment]
Looking at the call stack, it looks you are on an older version (before Feb 24, 2018). I also noticed that the client was trying to reconnect to Discord, which could mean that you had an issue your connection to Discord.

**Comment by HunterCop224** [comment]
As for close code 1006, it seems to be something about an abnormal close, as if the connection was closing already but didn't close properly? As said I'm new to a lot of this stuff not sure if I'm right about that. found these two pages when doing some digging:

https://github.com/theturtle32/WebSocket-Node/issues/254
https://github.com/websockets/ws/issues/799

**Comment by HunterCop224** [comment]
Ouch well my mistake then, I'll recompile SleepyDiscord and see what happens. I have had a strange network issue with an unrelated game which didn't want to work behind one router but would with another, ill test that too.

**Comment by HunterCop224** [comment]
That sounds like a good idea, especially if it turns out to be something I cant solve on my end. Normally just restarting it works fine. And is there any way to check the version of SleepyDiscord from within visual studio or by calling a function?

**Comment by yourWaifu** [comment]
No, there isn't a way to get the version of Sleepy Discord other then dates and numbers from git.

**Comment by HunterCop224** [comment]
Ok that's fine. And the latest build worked reliably for over 12 hours however the same issue came though, a 1006 again but with a different stack trace.
![lyra](https://user-images.githubusercontent.com/34903084/36929826-fc8f3c38-1e5b-11e8-8024-20063eea378a.PNG)

Not sure if that means anything different, ill start diagnosing to see if It's a network issue on my end.

**Comment by HunterCop224** [comment]
The bot has been running for 48 hours straight and the above is the only time it has crashed in the past 3 days. I haven't modified anything with my network yet, Thew only thing to note is an "Error 5001: Unexpected or unknown event occurred" a few hours ago but the bot is still functioning fine. I'm fine with this issue being closed, if I discover it's still happening again i'll do a bunch of looking into my home network to make sure that it's not the hardware firewall causing the issue. However it is interesting that the update alone has reduced the crashing.

**Comment by HunterCop224** [comment]
Recieved another crash today, just like the one posted above that happened 2018-03-02, however the last line was different. The local error error code was 1006 as always, however the remote error code was 1001 "remote:[1001]". Which means "going away" such as the server going down or disconnecting.

I think the easiest, and maybe the best, solution would be to just attempt to reconnect or restart the client in situations like this. I'd love it if it never disconnected but I have a feeling that even if I were to use a different library for the bot I would still have this issue.

Thank you for the help, I'll look into automatically restarting it until then.

**Comment by yourWaifu** [comment]
Well, the client should try to reconnect on bad connections or when Discord tells the client to do so. However, I have a feeling that the crash happens during the reconnect. I'll try to simulate different bad connection situations. I'm currently working on some major features, so I'm currently juggling between the two.

**Comment by HunterCop224** [comment]
That's absolutely fine, and as said before I have a hardware firewall that may be ID'ing the re-connection as something else and dropping the packets. If that turns out to be the case i'll go into more detail about it. And do you happen to know all the ports that are used for the Discord API/SleepyDiscord?

**Comment by yourWaifu** [comment]
The ports that are used depends on the Web Sockets library that Sleepy Discord is using. However, I'm sure it's 443 because Web Socket was "designed to work over HTTP ports".

**Comment by HunterCop224** [comment]
I have some bad news. And some interesting news.

I have 100% reset my home internet connection and am now completely on factory defaults and only using the modem/router combo provided by AT&T, a Pace 5268AC Modem/Router. So my network is as normal and standard as it can be, everything plugs directly into the Pace with no switches or routers or anything behind it.

Ill start by saying that I have not updated the bot I'm running since March 8th to fix a bug with one of the commands. Behavior has just about been the same even with everything reset on a Windows 10 machine running build 16299.309. Bot runs for 2-48 hours and crashes as mentioned before.

However when running it on my server (Windows Server 2016 build 14393.2007, way older build) I do not get "crashes". The first time running it the bot ran for 5 days, however the bot account went offline and stopped receiving commands around that time. No errors or messages from the CLI window but it was not receiving commands. And now I can only send it one command before it stops receiving messages entirely from what I can tell. I can use one command and then it no longer accepts commands or prints any output in the CLI.

I have not changed the source code at all and am still using the same build from March 8th which never had this problem. Unfortunately some people have come to rely on the bot and want it working and are getting impatient with me about it. So I will be using another bot library until I can rely on SleepyDiscord.

I still have full faith in you and SleepyDiscord, and would love nothing more than to use this library. I will be more than happy to provide any of the source code for the bot privately to you (as I'm an amateur with C++ and no one should read my awful code) if you want to see if I've programmed something wrong or am doing something to cause these issues unintentionally.

I'll still be subscribed to this thread as long as it's open and am fine with providing or doing things to help get this bug fixed. If you need anything, just ask!

**Comment by yourWaifu** [comment]
Sorry I haven't said anything in a while, but I've have been making improvements to how the library handles websocket connections. There are actually a lot of changes, and I still don't feel that they are ready to be released. Those change currently don't fix the issues but they should help it easier to fix some of those issues. As a response, I'll be updating the develop branch with those changes.

**Comment by HunterCop224** [comment]
That's absolutely fine, and I was restarting the bot then doing some test commands myself then telling users the bot was back, then they would proceed to type in capital `i`'s rather than lowercase `l`'s ...
l; daily == `l; daily`
I; daily == `I; daily`

So in reality SleepyDiscord may be in a state of full functionality for me on the Windows Server, but I'll have to let it run for a week again to verify that. Which if it does then it's definitely a combination of windows and network problems causing the issue. I'll investigate what caused the problem if I can verify that the problem is fixed.

Do not worry about not saying anything, I know you're working on a lot of things and I'm just keeping this ticket updated with info on the issue for now. Keep up the good work!

**Comment by HunterCop224** [comment]
This isn't for the latest develop branch [c8815a9]((https://github.com/yourWaifu/sleepy-discord/commit/c8815a940092ed334b1c839ad33acc00eee66ec7)) but for the branch I updated to yesterday, however I got some potentially useful information that specifically pertains to this. Recently I get [Local 1006 Remote 1001] errors but this time I've got an error message.
![capture](https://user-images.githubusercontent.com/34903084/38341869-73f2bc70-3840-11e8-8436-b196e680302c.PNG)

So after some looking it might be related to one of these two issues.
[General WebSocket Issue](https://stackoverflow.com/questions/39668410/whats-disconnecting-my-websocket-connection-cloudflare-apaches-mod-proxy)
[Discord.Net Bot Issue](https://github.com/RogueException/Discord.Net/issues/130)

The first issue mentions that after 100 seconds of dormancy on the WebSocket it is closed.
Second issue is related to failing authentication after reconnecting when the WebSocket closes.

I'll build the development branch and see if I get any different behavior, since these issues seem to be directly related I thought i'd bring them up for reference. Haven't had any [Local 1006 Remote 1006] errors since the network change.

**Comment by HunterCop224** [comment]
I apologize for my inactivity. Finals hit and after I had issues remembering the process I used to compile and update SleepyDiscord from my project but all is good now. Over the past 12ish hours I've had a few disconnections but they have all reconnected successfully!

![capture](https://user-images.githubusercontent.com/34903084/40813921-df94ec8e-6502-11e8-9afc-dc9317b768f3.PNG)

I am also running Discord4J as a reference connection, it seems to disconnect at the same times and also reconnects successfully, so I do not think this is a SleepyDiscord specific problem for the disconnecting, but the reconnecting is and it seems to be fixed. 

I would like to leave it running for a few more days to see if any other issues arise, there does seem to be a ~45 second delay in the re-connection but this is a huge step forward as it is.

This is the development version from 2 days ago, branch 8fd6b7d I believe.

**Comment by Brandantl** [comment]
Put a breakpoints somewhere in the program and wait 5 to 10 minutes and click resume and it'll crash

**Comment by HunterCop224** [comment]
I think that should be a different issue if it is considered one, for this it was just normal operation.

Speaking of I had to restart it a few days ago but was able to let it run for a few days straight and strangely only got 3 disconnects again. And she reconnected every time. I think this issue is fixed!

![capture](https://user-images.githubusercontent.com/34903084/40964480-dc70408c-6870-11e8-9268-2acc89baa297.PNG)
