### ISSUE TITLE
Can not compile on linux

### ISSUE THREAD

**Issue by Jimbow500** [yourWaifu/sleepy-discord#54]
I keep getting this error

https://pastebin.com/bk1nZMQ4

**Comment by yourWaifu** [comment]
Hmm, it looks like you may have forgotten to link openSSL and maybe even Sleepy Discord. Make your have those in your list of libraries to link
```
-L/usr/lib -lsleepy_discord  -lcurl -lssl -lcrypto 
```

**Comment by Jimbow500** [comment]
Saying it can't find `-lsleepy_discord` I did install all of the required c++ libraries to the newest version

**Comment by Jimbow500** [comment]
I had a few things messed up, it wasn't your program but thank you for your time

**Comment by yourWaifu** [comment]
no problem
