### ISSUE TITLE
Issue compiling sample project

### ISSUE THREAD

**Issue by BranchieManchie** [yourWaifu/sleepy-discord#55]
Hi, I'm fairly new to these libraries, so it's entirely possible I royally screwed up somewhere while compiling. Regardless, whenever I try to compile the sample project (directly copy-pasted), I get these errors:

```
1>------ Build started: Project: BottyBoi, Configuration: Debug Win32 ------
1>Source.cpp
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xutility(2440): error C4996: 'std::copy::_Unchecked_iterators::_Deprecate': Call to 'std::copy' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xutility(2440): note: see declaration of 'std::copy::_Unchecked_iterators::_Deprecate'
1>c:\sleepy-discord\deps\include\websocketpp\frame.hpp(255): note: see reference to function template instantiation '_OutIt std::copy<uint8_t*,uint8_t*>(_InIt,_InIt,_OutIt)' being compiled
1>        with
1>        [
1>            _OutIt=uint8_t *,
1>            _InIt=uint8_t *
1>        ]
1>Done building project "BottyBoi.vcxproj" -- FAILED.
```

The first error is obvious enough, but the others have me stumped. It's entirely possible I'm just dumb, but I'd appreciate it if someone could make sense of these errors for me so I can fix the issues- specifically the last one about frame.hpp.

**Comment by yourWaifu** [comment]
Add _SCL_SECURE_NO_WARNINGS to your list of preprocessor definitions. https://yourwaifu.github.io/sleepy-discord/link.html#preprocessor-definitions

The error is basically saying that std::copy may by unsafe and the notes are saying where it's declared and other useful information. However, this maybe be an issue with websocket++. 

I'm going to close this as this should fix this issue.

**Comment by BranchieManchie** [comment]
Thank you. I believe that it is an issue with websocket++, since the error sends me to a file in the WS++ directories.
