### ISSUE TITLE
Visual Studio 2017 Compile Failure

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#57]
This code in websocketpp_websocket.cpp Line 62 

```
Timer WebsocketppWebsocketClient::schedule(std::function<void()> code, const time_t milliseconds) {
		auto& timer = this_client.set_timer(
			milliseconds,
			websocketpp::lib::bind(&handleTimers, websocketpp::lib::placeholders::_1, code)
		);
		return Timer([timer]() {
			timer->cancel();
		});
	}
```

Causes the build to fail because there is no such class called WebsocketppWebsocketClient. Commenting this out allowed the build to succeed in VS2017

Additionally, the Windows SDK (for some reason) is set in the build properties. This causes build failure on newer versions of the Windows SDK. But it's easy to re-target the project.

**Comment by yourWaifu** [comment]
change WebsocketppWebsocketClient to WebsocketppDiscordClient, the name difference comes from the differences between the master branch and the develop branch.
