### ISSUE TITLE
LibCurl and the Setup.py 

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#58]
LibCurl fails to install using the Setup.py.
```
Warning: The curl manual could not be integrated in the source. This means when
you build curl the manual will not be available (curl --man). Integration of
the manual is not required and a summary of the options will still be available
(curl --help). To integrate the manual your PATH is required to have
groff/nroff, perl and optionally gzip for compression.
```

Which causes build failure in the examples... or i'm an idiot. 

> 1>sleepy_discord.vcxproj -> C:\Users\Brandan Lasley\Downloads\yourWaifu-sleepy-discord-703813e\Release\sleepy_discord.lib
> 2>------ Rebuild All started: Project: hello, Configuration: Release Win32 ------
> 3>------ Rebuild All started: Project: rock-paper-scissors, Configuration: Release Win32 ------
> 2>example0.cpp
> 3>main.cpp
> 2>LINK : fatal error LNK1181: cannot open input file 'libcurl_a.lib'
> 2>Done building project "hello.vcxproj" -- FAILED.
> 3>LINK : fatal error LNK1181: cannot open input file 'libcurl_a.lib'
> 3>Done building project "rock-paper-scissors.vcxproj" -- FAILED.
> ========== Rebuild All: 1 succeeded, 2 failed, 0 skipped ==========

**Comment by yourWaifu** [comment]
it looks like you don't have libcurl_a.lib, the link below should tell how to get this file.
https://yourwaifu.github.io/sleepy-discord/link.html#preparing

**Comment by Brandantl** [comment]
Oh I didn't see that I was still in the compile documentation. Thanks!

**Comment by yourWaifu** [comment]
```1>sleepy_discord.vcxproj -> C:\Users\Brandan Lasley\Downloads\yourWaifu-sleepy-discord-703813e\Release\sleepy_discord.lib```
you compiled the library successfully. Linking is what you need to do now.

**Comment by Brandantl** [comment]
Thanks!

========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

**Comment by yourWaifu** [comment]
no problem
