### ISSUE TITLE
Develop branch and Linux complication. 

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#67]
I was going to try and find that stack corruption thing MSVC found with Valgrind but sleepy discord does not compile on Linux.

Using G++ or Clang.

![linxerr](https://user-images.githubusercontent.com/6909044/38655698-06d3f542-3dcb-11e8-9e67-565bf983ea31.PNG)

Missing asio_udp.h(?)

I was able to compile by deleting asio_udp.cpp (deleted header forgot to delete cpp?)

**Comment by yourWaifu** [comment]
I'm going to guess you don't have the asio library? If that's the cause maybe a false positive when detecting the asio library. I'm currently not at my computer, so it's hard to say.

**Comment by Brandantl** [comment]
The same error is on your Travis CI (and yes I have the library)

https://travis-ci.org/yourWaifu/sleepy-discord/builds/365378458?utm_source=github_status&utm_medium=notification
