### ISSUE TITLE
Channel Type

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#70]
auto ch = DiscordPtr->getChannel(message.channelID);
std::cout << ch->type;

gives a bunch of random numbers. I assume because type is an integer and not a string.

**Comment by Brandantl** [comment]
There's actually 2 instances where I've had to parse my own JSON because the library either crashed doing so or failed to get the type right.
https://github.com/Brandantl/IntenseCoin-TipBot/blob/develop/src/Discord.cpp#L20

int ITNS_TIPBOT::getDiscordChannelType(SleepyDiscord::Snowflake<SleepyDiscord::Channel> id)
std::string ITNS_TIPBOT::getDiscordDMChannel(DiscordID id)

**Comment by yourWaifu** [comment]
Hmm, I'll do some testing and see what's wrong. I'll try to get back to you with results.
