### ISSUE TITLE
Line breaks in the bot's message

### ISSUE THREAD

**Issue by Skorpo** [yourWaifu/sleepy-discord#80]
I am unable to utilize line breaks in the sendMessage function. For instance:

```C
sendMessage(message.channelID, "h smash\nsends all smash-related links");
```

This doesn't put anything in the chat, and puts the following in the command prompt:

> Error 400: The request was improperly formatted, or the server couldn't understand it
> Error 50006: Cannot send an empty message

**Comment by yourWaifu** [comment]
```sendMessage(message.channelID, "h smash\\nsends all smash-related links");```
This is intended behavior. https://yourwaifu.github.io/sleepy-discord/documentation.html#sendmessage
