### ISSUE TITLE
Cannot open libcurl_a.lib

### ISSUE THREAD

**Issue by ICantIHavePoney** [yourWaifu/sleepy-discord#84]
Hello

I have followed all your tutorials, but when I want to build my test project or a sample project I got this message displayed in the console.

Do you have any idea ? 'Cause I'm out of it

**Comment by yourWaifu** [comment]
You are missing libcurl_a.lib, https://yourwaifu.github.io/sleepy-discord/link.html#preparing
How to compile only tells you how to compile the library. There are other steps you need to take to link it to your code.

**Comment by ICantIHavePoney** [comment]
I had curl compiled, and libcurl_a.lib appears in the builds folder of curl, and the errors disapeared, but some new errors popped out. 

![image](https://user-images.githubusercontent.com/17005904/41628510-27241940-7425-11e8-9936-377e28476ba9.png)

**Comment by ICantIHavePoney** [comment]
Okay, I'm just a fuckin' goddumb (I know this word doesn't exist, but I can't find one that fits better), I had skipped the part where you move the lib and include to the deps folder ><'.


But now on, I'm getting this

![image](https://user-images.githubusercontent.com/17005904/41628686-f4aa358e-7425-11e8-832b-6ccabaa2b6e4.png)

And I'm very confused by the warning, which said there is a conflict between library type x64 and the computer type x86.

**Comment by yourWaifu** [comment]
are you sure you also didn't skip this step? https://yourwaifu.github.io/sleepy-discord/link.html#add-dependencies

**Comment by ICantIHavePoney** [comment]
nope, I'm trying to build the hello sample project, and it seems to have every thing well setted up

**Comment by yourWaifu** [comment]
As for the warning at the top see where it says Debug and x64, switch that to x86 or win32.

**Comment by ICantIHavePoney** [comment]
I'm already in win32

**Comment by yourWaifu** [comment]
Most likely a conflict with another library. Other then that I was able to recreate your issue by not linking libcurl_a.lib 
![image](https://user-images.githubusercontent.com/16181109/41629138-df0b8cc6-73f5-11e8-8d21-0160711fd0f4.png)
ignore the errors about voiceConnection, that's because of my unfinished code.

**Comment by ICantIHavePoney** [comment]
Well, I've checked again, but no, the dependencies is well linked 

![image](https://user-images.githubusercontent.com/17005904/41629742-7479feac-742b-11e8-938b-d8b3d82b98b0.png)

**Comment by yourWaifu** [comment]
Maybe try recompiling libcurl, you have compile it incorrectly causing it to find the symbols.

**Comment by yourWaifu** [comment]
Oops ignore the commit mentioned, it was a mistake
