### ISSUE TITLE
users permissions

### ISSUE THREAD

**Issue by UsernameMs** [yourWaifu/sleepy-discord#91]
How I can check users permissions?

**Comment by yourWaifu** [comment]
Issues isn't really for asking questions

roles are stored in the server and serverMember. However the current server class doesn't have roles or members.

**Comment by UsernameMs** [comment]
So that library can't check users permissions?

**Comment by yourWaifu** [comment]
It can but not easily. To do so you'll have to parse the server object to get the list of roles.

**Comment by UsernameMs** [comment]
Then, what class I need to use?

**Comment by yourWaifu** [comment]
You'll need a few things. I wouldn't call them classes as they are JSON object or number. We will need the Guild Member, which you'll need the server or server ID and user ID to get. This will give us the IDs of roles that the user has on a server. From there we check their permissions from their role.

You could also get them via the JSON or string form from the function getServers.

Not to mention, channels can override permissions so you'll also need to check those as well.

Once you have the premission, you can check if the user has a specific permission using a bitwise and.

**Comment by UsernameMs** [comment]
So I have ServerID and UserID, What now?

**Comment by yourWaifu** [comment]
Sorry it took so long, I was working on other project also adding this feature also made the library use a bit more ram and cpu. On Debug, it's a massive difference, but on release, the difference is noticeable but not as big.

Other then that, in commit fb0e517, I added
```cpp
Permission getPermissions(const Server& server, const ServerMember& member, const Channel& channel) 
```
and
```cpp
constexpr bool hasPremission(const Permission& target, const Permission& permission)
```

Here is an example,
```cpp
SleepyDiscord::Permission permissions = SleepyDiscord::getPermissions(server, server.members[1], server.channels[0]);
if (hasPremission(permissions, SleepyDiscord::Permission::MANAGE_CHANNELS))
	std::cout << "True\n";
```
possible output
```
True
```

**Comment by UsernameMs** [comment]
No problem and Thanks

**Comment by UsernameMs** [comment]
One problem, I have got that erros: https://pastebin.com/S0znVgH5
code
`
		if (message.startsWith("test"))
		{
			SleepyDiscord::Permission permissions = SleepyDiscord::getPermissions(server, server.members[1], server.channels[0]);
			if (hasPremission(permissions, SleepyDiscord::Permission::MANAGE_CHANNELS))
				deleteChannel(message.channelID);
			else
				sendMessage(message.channelID, "Nope");
		}
`

**Comment by yourWaifu** [comment]
It looks like you declared server to be a std:: list. Can I see the declaration of server

**Comment by UsernameMs** [comment]
`
using SleepyDiscord::DiscordClient::DiscordClient;

	void onServer(SleepyDiscord::Server server) {
		servers.push_front(server);
	}

	std::list<SleepyDiscord::Server> servers;

	void onMessage(SleepyDiscord::Message message)
	{

		SleepyDiscord::Snowflake<SleepyDiscord::Server> serverID;
		auto server = std::find_if(servers.begin(), servers.end(), [&message](SleepyDiscord::Server& server) {
			auto result = message.channelID.findObject(server.channels);
			return result != server.channels.end();
		});
`

**Comment by yourWaifu** [comment]
Ahh, I see. server is a std::list<SleepyDiscord::Server>::iterator. You may want to read up on InputIterators here https://en.cppreference.com/w/cpp/named_req/InputIterator. In summery, To fix your issue, you need to using *server get a reference of the server and server->members to access members.

I also recommend read up on find as well https://en.cppreference.com/w/cpp/algorithm/find.

**Comment by UsernameMs** [comment]
How can I do it?

**Comment by yourWaifu** [comment]
``SleepyDiscord::getPermissions(*server, server->members[1], server->channels[0]);``

You may also want to do ``if (server != servers.end())`` to check if a server was found.

I recommend you read up on iterators and find_if and getting an understanding of what the code above is doing before blindly copying and pasting code to avoid confusion.

**Comment by UsernameMs** [comment]
So I have to wait for new update?
