### ISSUE TITLE
onReady virtual prototype changed

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#96]
Why is onReady now 		
> virtual void onReady             (std::string* jsonMessage);

and not 

> virtual void onReady             (Ready        readyData    );

as the prototype is listed here in the documentation 

> #include <sleepy_discord>
> 
> class MyDiscordClient : public SleepyDiscord::DiscordClient {
> public:
>     void onReady(SleepyDiscord::Ready data) {
>         client.addReaction("channel id", "message id", "%F0%9F%98%95");
>     }
> }
> 
> int main() {
>     SleepyDiscord::DiscordClient client("token");
> }

https://yourwaifu.github.io/sleepy-discord/documentation.html#addreaction

**Comment by yourWaifu** [comment]
issues isn't for asking questions, but I'll answer them anyway. It simplify the library code on my end.

**Comment by Brandantl** [comment]
What? The documentation is wrong as void onReady(SleepyDiscord::Ready data) is no longer the correct way to use onReady.

**Comment by yourWaifu** [comment]
``virtual void onReady (std::string* jsonMessage);`` is the old version and it's in develop
``virtual void onReady (Ready readyData );`` is the new version that's about to be merged soon.

https://github.com/yourWaifu/sleepy-discord/blob/develop/include/sleepy_discord/client.h#L248

**Comment by Brandantl** [comment]
It's also in master https://github.com/yourWaifu/sleepy-discord/blob/master/include/sleepy_discord/client.h#L238

**Comment by yourWaifu** [comment]
I'm aware that master is still using the old version because it's a breaking change, that's why it's in develop and not master. I have a list of changes that would break other's code that I plan on placing in the docs.

**Comment by Brandantl** [comment]
I saw the old message before you edited it clarifying its NOT in develop. I saw commits in master and thought you pushed over all the changes from develop. My mistake but it is confusing the documentation addresses stuff in the develop branch and not the current release branch (master).
