### ISSUE TITLE
does not exist or is not a namespace

### ISSUE THREAD

**Issue by Moulijin** [yourWaifu/sleepy-discord#97]
I followed the documentation step by step but, I am getting 22 error that SleepDiscord and its functions does not exist or is not a namespace

![image](https://user-images.githubusercontent.com/2942447/42415774-bcfeac44-820f-11e8-973c-fe8270b17dc0.png)

**Comment by yourWaifu** [comment]
I'm going to guess that you are missing websocket++. Check that you have a folder named websocketpp inside deps/include.

**Comment by Moulijin** [comment]
I have it

![image](https://user-images.githubusercontent.com/2942447/42416342-e83c90e0-8220-11e8-8f3c-9579a650b382.png)

**Comment by yourWaifu** [comment]
ok good make sure you files in there but are you compiling this using the config from the example folder or did you do the config yourself using the link guide? if so, I would like to see your include directories.

**Comment by Moulijin** [comment]
ok, now it's showing 

![image](https://user-images.githubusercontent.com/2942447/42416489-894f8a5c-8224-11e8-8aa2-b7ecceba80a1.png)

**Comment by yourWaifu** [comment]
did you compile tho?

**Comment by Moulijin** [comment]
yes now it showing
![image](https://user-images.githubusercontent.com/2942447/42416504-e51c7372-8224-11e8-9ea8-006fee95cb3e.png)

**Comment by yourWaifu** [comment]
Did you make the change to all configurations, both Release and Debug?

**Comment by Moulijin** [comment]
yes, still same error

**Comment by yourWaifu** [comment]
the include directories window, right below the list of directories is the list of evaluated values. Make sure that they lead to the correct folders. For example:
```
C:\Users\steve\Documents\nsprojects\sleepy_discord\deps\include
```

**Comment by yourWaifu** [comment]
I want you to try this, and show me the result. right click on ``"sleepy_discord/websocketpp_websocket.h"``, and left click on ``Open Document``. And do the same thing for ``<websocketpp/config/asio_client.hpp>`` Tell me what happens. Does it go to a file with ``#define NONEXISTENT_WEBSOCKETPP`` or does it go somewhere else?

**Comment by Moulijin** [comment]
![image](https://user-images.githubusercontent.com/2942447/42416780-d2881308-822c-11e8-818a-4a628283b6ca.png)

**Comment by yourWaifu** [comment]
umm that's not right
First of all, the path to asio_client is going to the wrong file. It should be going to deps\websocketpp\config\asio_client.
2nd, the path doesn't make any sense, shouldn't include come before ``sleepy_discord\IncludeNonexistent`` according to your screenshot?
3rd, you shouldn't be hard coding the full path to the file, you're making it harder to compile it on other machines.

**Comment by Moulijin** [comment]
ok, I managed to fix it. Now just getting nullptr_t error 
![image](https://user-images.githubusercontent.com/2942447/42416916-ce5596a4-822f-11e8-8be1-d32cdfd6a480.png)

**Comment by yourWaifu** [comment]
> ok, I managed to fix it
it would be great if you example if you know how you fixed it in case others come here and find this

What version of the library are you using, because the current version doesn't have that variable. Other then that, it should be ```std::condition_variable* condition = nullptr```. https://github.com/yourWaifu/sleepy-discord/blob/master/include/sleepy_discord/client.h https://github.com/yourWaifu/sleepy-discord/commit/3580a2b95179938b4d1f0338f60f4c797044e30a#diff-b17ee23637b770c383c1a16159a23cbaL298

**Comment by Moulijin** [comment]
What i did is I replaced the hard coded path to #include <websocketpp/config/asio_client.hpp> and gave me the std::condition_variable condition = nullptr error. I added the asterisk and worked but, now is giving me

**Comment by Moulijin** [comment]
Now, it's just this error 
![image](https://user-images.githubusercontent.com/2942447/42420965-9442a4e0-8282-11e8-8931-196bb4c64f2c.png)

**Comment by yourWaifu** [comment]
Add ``Ws2_32.lib`` to your list of additional dependences and make sure you do it to all configurations.

**Comment by Moulijin** [comment]
Same issue

**Comment by Moulijin** [comment]
Issue resolved. Installed openssl through NuGet.

![image](https://user-images.githubusercontent.com/2942447/42424428-fc082314-82c0-11e8-805c-c8cbae8e4ece.png)

**Comment by Moulijin** [comment]
Good news I am able to run it. When I try to enter a sendmessage, I get an error. I tried to search through issues that other post before posting but, was not able to find one. 
![image](https://user-images.githubusercontent.com/2942447/42430510-934e9838-82f4-11e8-9ef4-c1841e227f0b.png)

**Comment by yourWaifu** [comment]
The error are being caused by the fact that it's looking for functions that aren't defined. However, those functions have to have been declared else you would get Identifier not found errors. 

> I completed deleted sleepy_discord and tried again but , same error results

If you deleted them you should get different errors such can't find include file or can't link file because the files shouldn't exist anymore. If you are get the same errors after deleting the library then the library has to still be present elsewhere else.

I'm going to guess that the wrong files are being included and that you have some old version that's bring included. Use this to figure out what files are being included. https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files

Try opening the files and see if they lead to the same files that you just screenshoted.

**Comment by yourWaifu** [comment]
try using the override specifier, this will tell the compiler that you want this function to override a function and give an error when it doesn't override. https://en.cppreference.com/w/cpp/language/override

Take a look at this. https://github.com/yourWaifu/sleepy-discord/blob/master/include/sleepy_discord/client.h#L238
add ``std::string* jsonMessage``
also a little note, that I will change this in the future. https://github.com/yourWaifu/sleepy-discord/blob/develop/include/sleepy_discord/client.h#L248

**Comment by Moulijin** [comment]
already exists 
![image](https://user-images.githubusercontent.com/2942447/42483341-c3b2a34a-83a1-11e8-9e18-3588d6e8320a.png)

**Comment by yourWaifu** [comment]
I don't think you understand what I was trying to tell you. Let me making really clear.
change this
```
void onReady() {
```
to this
```
void onReady(std::string* jsonMessage) override {
```

**Comment by Moulijin** [comment]
oh doh, my fault. ok looks like its working now 
![image](https://user-images.githubusercontent.com/2942447/42483546-04c30fc2-83a3-11e8-92e2-4830d2f84bb3.png)

**Comment by Moulijin** [comment]
everything works now. Thank you so much for your help!
